insert into tienda (id_tienda, direccion, ciudad) values (1, 'PO Box 35293', 'Kalumpang');
insert into tienda (id_tienda, direccion, ciudad) values (2, '7th Floor', 'Caiyuan');
insert into tienda (id_tienda, direccion, ciudad) values (3, 'Suite 9', 'Miami');
insert into tienda (id_tienda, direccion, ciudad) values (4, 'Apt 251', 'Majie');
insert into tienda (id_tienda, direccion, ciudad) values (5, '13th Floor', 'Geoktschai');
insert into tienda (id_tienda, direccion, ciudad) values (6, 'Apt 380', 'Göteborg');
insert into tienda (id_tienda, direccion, ciudad) values (7, 'Apt 734', 'Sidi Slimane');
insert into tienda (id_tienda, direccion, ciudad) values (8, 'Apt 339', 'Trondheim');
insert into tienda (id_tienda, direccion, ciudad) values (9, 'Apt 1780', 'Ampanihy');
insert into tienda (id_tienda, direccion, ciudad) values (10, 'Room 1654', 'Zaindainxoi');
insert into tienda (id_tienda, direccion, ciudad) values (11, 'Apt 759', 'Bum Bum');
insert into tienda (id_tienda, direccion, ciudad) values (12, 'Suite 64', 'Darłowo');
insert into tienda (id_tienda, direccion, ciudad) values (13, 'PO Box 85463', 'Xianhe');
insert into tienda (id_tienda, direccion, ciudad) values (14, '14th Floor', 'Alīābad');
insert into tienda (id_tienda, direccion, ciudad) values (15, '7th Floor', 'Hudson');
insert into tienda (id_tienda, direccion, ciudad) values (16, 'Suite 31', 'Baiheshan');
insert into tienda (id_tienda, direccion, ciudad) values (17, 'Suite 11', 'Glafirovka');
insert into tienda (id_tienda, direccion, ciudad) values (18, 'Suite 82', 'Oeleon');
insert into tienda (id_tienda, direccion, ciudad) values (19, 'Room 1047', 'Krajan Suco');
insert into tienda (id_tienda, direccion, ciudad) values (20, 'Suite 39', 'El Refugio');
insert into tienda (id_tienda, direccion, ciudad) values (21, 'Apt 1150', 'Naviraí');
insert into tienda (id_tienda, direccion, ciudad) values (22, 'Suite 39', 'Irirum');
insert into tienda (id_tienda, direccion, ciudad) values (23, 'PO Box 73311', 'Matanog');
insert into tienda (id_tienda, direccion, ciudad) values (24, 'Apt 246', 'Bangbayang');
insert into tienda (id_tienda, direccion, ciudad) values (25, 'Suite 46', 'Lipsko');
insert into tienda (id_tienda, direccion, ciudad) values (26, '19th Floor', 'Ivanteyevka');
insert into tienda (id_tienda, direccion, ciudad) values (27, 'Suite 35', 'Lianran');
insert into tienda (id_tienda, direccion, ciudad) values (28, '7th Floor', 'Hongxi');
insert into tienda (id_tienda, direccion, ciudad) values (29, '12th Floor', 'Buur Gaabo');
insert into tienda (id_tienda, direccion, ciudad) values (30, 'Apt 1003', 'Sandefjord');
insert into tienda (id_tienda, direccion, ciudad) values (31, 'Room 1464', 'Peñal');
insert into tienda (id_tienda, direccion, ciudad) values (32, 'Room 1811', 'Xuanbao');
insert into tienda (id_tienda, direccion, ciudad) values (33, '6th Floor', 'Sélibabi');
insert into tienda (id_tienda, direccion, ciudad) values (34, 'Room 974', 'Пласница');
insert into tienda (id_tienda, direccion, ciudad) values (35, 'Apt 182', 'Río Campo');
insert into tienda (id_tienda, direccion, ciudad) values (36, 'Apt 229', 'Sacramento');
insert into tienda (id_tienda, direccion, ciudad) values (37, 'Suite 52', 'Qingfeng');
insert into tienda (id_tienda, direccion, ciudad) values (38, '14th Floor', 'Kitapak');
insert into tienda (id_tienda, direccion, ciudad) values (39, 'PO Box 38976', 'Krajan Keboromo');
insert into tienda (id_tienda, direccion, ciudad) values (40, '18th Floor', 'Perelhal');
insert into tienda (id_tienda, direccion, ciudad) values (41, '5th Floor', 'Morbatoh');
insert into tienda (id_tienda, direccion, ciudad) values (42, 'PO Box 76793', 'Loboniki');
insert into tienda (id_tienda, direccion, ciudad) values (43, 'Suite 1', 'Fuwah');
insert into tienda (id_tienda, direccion, ciudad) values (44, 'Apt 1380', 'Erqu');
insert into tienda (id_tienda, direccion, ciudad) values (45, 'Suite 48', 'Guararema');
insert into tienda (id_tienda, direccion, ciudad) values (46, 'PO Box 23819', 'Martil');
insert into tienda (id_tienda, direccion, ciudad) values (47, '7th Floor', 'Quebrada de Arena');
insert into tienda (id_tienda, direccion, ciudad) values (48, '5th Floor', 'Panagyurishte');
insert into tienda (id_tienda, direccion, ciudad) values (49, 'Suite 46', 'Kuantan');
insert into tienda (id_tienda, direccion, ciudad) values (50, '12th Floor', 'Taouima');
insert into tienda (id_tienda, direccion, ciudad) values (51, 'Apt 886', 'Lovisa');
insert into tienda (id_tienda, direccion, ciudad) values (52, 'PO Box 56133', 'Aţ Ţawīlah');
insert into tienda (id_tienda, direccion, ciudad) values (53, 'PO Box 76694', 'Araxá');
insert into tienda (id_tienda, direccion, ciudad) values (54, 'Suite 66', 'Ngangguk');
insert into tienda (id_tienda, direccion, ciudad) values (55, 'PO Box 22546', 'Nahura');
insert into tienda (id_tienda, direccion, ciudad) values (56, 'Room 1740', 'Tubungan');
insert into tienda (id_tienda, direccion, ciudad) values (57, '6th Floor', 'Jardim');
insert into tienda (id_tienda, direccion, ciudad) values (58, 'Suite 100', 'Aguadas');
insert into tienda (id_tienda, direccion, ciudad) values (59, 'Room 1209', 'Gubkinskiy');
insert into tienda (id_tienda, direccion, ciudad) values (60, '8th Floor', 'Nizhniye Achaluki');
insert into tienda (id_tienda, direccion, ciudad) values (61, '14th Floor', 'Ijebu-Ife');
insert into tienda (id_tienda, direccion, ciudad) values (62, '11th Floor', 'Novotroitsk');
insert into tienda (id_tienda, direccion, ciudad) values (63, 'PO Box 76340', 'Göteborg');
insert into tienda (id_tienda, direccion, ciudad) values (64, '7th Floor', 'Sydney');
insert into tienda (id_tienda, direccion, ciudad) values (65, '5th Floor', 'Xihongmen');
insert into tienda (id_tienda, direccion, ciudad) values (66, 'Apt 413', 'Lefengzhen');
insert into tienda (id_tienda, direccion, ciudad) values (67, 'PO Box 77242', 'Kogon');
insert into tienda (id_tienda, direccion, ciudad) values (68, 'PO Box 80142', 'Tsivil’sk');
insert into tienda (id_tienda, direccion, ciudad) values (69, 'Room 1951', 'Lincha');
insert into tienda (id_tienda, direccion, ciudad) values (70, 'Suite 78', 'Roma');
insert into tienda (id_tienda, direccion, ciudad) values (71, 'Apt 1697', 'Biao');
insert into tienda (id_tienda, direccion, ciudad) values (72, 'Suite 42', 'Quimbaya');
insert into tienda (id_tienda, direccion, ciudad) values (73, 'Room 1343', '‘Akko');
insert into tienda (id_tienda, direccion, ciudad) values (74, 'PO Box 46119', 'Chunghwa');
insert into tienda (id_tienda, direccion, ciudad) values (75, 'Apt 1057', 'Yangsan');
insert into tienda (id_tienda, direccion, ciudad) values (76, 'Apt 724', 'Ji’an');
insert into tienda (id_tienda, direccion, ciudad) values (77, 'Room 1947', 'Kang');
insert into tienda (id_tienda, direccion, ciudad) values (78, 'Suite 20', 'Paris 19');
insert into tienda (id_tienda, direccion, ciudad) values (79, 'PO Box 22445', 'Zhujiapu');
insert into tienda (id_tienda, direccion, ciudad) values (80, 'Apt 1373', 'Sudimanik');
insert into tienda (id_tienda, direccion, ciudad) values (81, 'Room 161', 'Zhoupi');
insert into tienda (id_tienda, direccion, ciudad) values (82, 'Suite 97', 'Delmiro Gouveia');
insert into tienda (id_tienda, direccion, ciudad) values (83, '4th Floor', 'Starotitarovskaya');
insert into tienda (id_tienda, direccion, ciudad) values (84, 'Room 1659', 'Bendo');
insert into tienda (id_tienda, direccion, ciudad) values (85, 'Room 932', 'Mander');
insert into tienda (id_tienda, direccion, ciudad) values (86, '20th Floor', 'Port Elizabeth');
insert into tienda (id_tienda, direccion, ciudad) values (87, 'Apt 486', 'Cisadap');
insert into tienda (id_tienda, direccion, ciudad) values (88, 'PO Box 6110', 'Banī an Nahārī');
insert into tienda (id_tienda, direccion, ciudad) values (89, 'Room 156', 'Fundación');
insert into tienda (id_tienda, direccion, ciudad) values (90, 'PO Box 46325', 'Sanjia');
insert into tienda (id_tienda, direccion, ciudad) values (91, 'Suite 17', 'Gununglarang');
insert into tienda (id_tienda, direccion, ciudad) values (92, '14th Floor', 'Batken');
insert into tienda (id_tienda, direccion, ciudad) values (93, 'Apt 1245', 'Saño');
insert into tienda (id_tienda, direccion, ciudad) values (94, 'Apt 45', 'Banjar Penyalin');
insert into tienda (id_tienda, direccion, ciudad) values (95, 'PO Box 9513', 'Strelka');
insert into tienda (id_tienda, direccion, ciudad) values (96, 'PO Box 21806', 'Al Bājūr');
insert into tienda (id_tienda, direccion, ciudad) values (97, '6th Floor', 'Radenković');
insert into tienda (id_tienda, direccion, ciudad) values (98, 'Room 1636', 'Rukem');
insert into tienda (id_tienda, direccion, ciudad) values (99, 'Apt 1628', 'Odiong');
insert into tienda (id_tienda, direccion, ciudad) values (100, 'PO Box 59181', 'Hūn');
insert into tienda (id_tienda, direccion, ciudad) values (101, '3rd Floor', 'Pau');
insert into tienda (id_tienda, direccion, ciudad) values (102, 'Apt 717', 'Konispol');
insert into tienda (id_tienda, direccion, ciudad) values (103, '5th Floor', 'Agra');
insert into tienda (id_tienda, direccion, ciudad) values (104, 'Suite 7', 'Srinjine');
insert into tienda (id_tienda, direccion, ciudad) values (105, 'Apt 24', 'Tangquan');
insert into tienda (id_tienda, direccion, ciudad) values (106, '13th Floor', 'Bandhagen');
insert into tienda (id_tienda, direccion, ciudad) values (107, 'Suite 48', 'Sande São Lourenço');
insert into tienda (id_tienda, direccion, ciudad) values (108, 'Suite 40', 'Jiatou');
insert into tienda (id_tienda, direccion, ciudad) values (109, 'Apt 88', 'Kongsvinger');
insert into tienda (id_tienda, direccion, ciudad) values (110, 'PO Box 46188', 'Macheng');
insert into tienda (id_tienda, direccion, ciudad) values (111, 'PO Box 52211', 'Rio das Ostras');
insert into tienda (id_tienda, direccion, ciudad) values (112, 'PO Box 14736', 'Shalushka');
insert into tienda (id_tienda, direccion, ciudad) values (113, 'Suite 75', 'Antofagasta');
insert into tienda (id_tienda, direccion, ciudad) values (114, '16th Floor', 'Matanza');
insert into tienda (id_tienda, direccion, ciudad) values (115, '8th Floor', 'Kangani');
insert into tienda (id_tienda, direccion, ciudad) values (116, 'PO Box 84998', 'Atamanovka');
insert into tienda (id_tienda, direccion, ciudad) values (117, 'Suite 63', 'Duma');
insert into tienda (id_tienda, direccion, ciudad) values (118, 'PO Box 71175', 'Kebonan');
insert into tienda (id_tienda, direccion, ciudad) values (119, 'Suite 6', 'Uspenskoye');
insert into tienda (id_tienda, direccion, ciudad) values (120, 'Suite 40', 'Novopokrovka');
insert into tienda (id_tienda, direccion, ciudad) values (121, '12th Floor', 'Sampungu');
insert into tienda (id_tienda, direccion, ciudad) values (122, 'Apt 1880', 'Chafé');
insert into tienda (id_tienda, direccion, ciudad) values (123, 'Room 515', 'San Miguel de Cauri');
insert into tienda (id_tienda, direccion, ciudad) values (124, 'Apt 956', 'Uchaly');
insert into tienda (id_tienda, direccion, ciudad) values (125, 'Apt 266', 'Comal');
insert into tienda (id_tienda, direccion, ciudad) values (126, 'PO Box 53815', 'Suining');
insert into tienda (id_tienda, direccion, ciudad) values (127, 'Room 1605', 'Quinta dos Frades');
insert into tienda (id_tienda, direccion, ciudad) values (128, '13th Floor', 'Drosiá');
insert into tienda (id_tienda, direccion, ciudad) values (129, '3rd Floor', 'Gandara');
insert into tienda (id_tienda, direccion, ciudad) values (130, 'PO Box 31996', 'Selenicë');
insert into tienda (id_tienda, direccion, ciudad) values (131, 'PO Box 47166', 'Marília');
insert into tienda (id_tienda, direccion, ciudad) values (132, 'PO Box 89811', 'Yartsevo');
insert into tienda (id_tienda, direccion, ciudad) values (133, '10th Floor', 'Washington');
insert into tienda (id_tienda, direccion, ciudad) values (134, 'Room 1110', 'Harstad');
insert into tienda (id_tienda, direccion, ciudad) values (135, 'PO Box 90982', 'Glugu');
insert into tienda (id_tienda, direccion, ciudad) values (136, 'Suite 62', 'Sueyoshichō-ninokata');
insert into tienda (id_tienda, direccion, ciudad) values (137, 'Apt 1167', 'Khiwa');
insert into tienda (id_tienda, direccion, ciudad) values (138, 'Suite 13', 'Machala');
insert into tienda (id_tienda, direccion, ciudad) values (139, '17th Floor', 'Jetaral');
insert into tienda (id_tienda, direccion, ciudad) values (140, 'PO Box 59320', 'Potosí');
insert into tienda (id_tienda, direccion, ciudad) values (141, 'PO Box 42171', 'Georgīevka');
insert into tienda (id_tienda, direccion, ciudad) values (142, 'PO Box 72934', 'Tarīm');
insert into tienda (id_tienda, direccion, ciudad) values (143, 'PO Box 18205', 'Imbituva');
insert into tienda (id_tienda, direccion, ciudad) values (144, 'Apt 1801', 'Buea');
insert into tienda (id_tienda, direccion, ciudad) values (145, '19th Floor', 'Dajin');
insert into tienda (id_tienda, direccion, ciudad) values (146, 'PO Box 32219', 'Changzhi');
insert into tienda (id_tienda, direccion, ciudad) values (147, 'Suite 24', 'Tomioka');
insert into tienda (id_tienda, direccion, ciudad) values (148, 'Apt 256', 'Smętowo Graniczne');
insert into tienda (id_tienda, direccion, ciudad) values (149, 'Apt 1386', 'Huangzhuang');
insert into tienda (id_tienda, direccion, ciudad) values (150, 'PO Box 33160', 'Novais');
insert into tienda (id_tienda, direccion, ciudad) values (151, 'Room 236', 'Kolç');
insert into tienda (id_tienda, direccion, ciudad) values (152, 'Suite 16', 'Gambiran');
insert into tienda (id_tienda, direccion, ciudad) values (153, 'PO Box 21784', 'Avignon');
insert into tienda (id_tienda, direccion, ciudad) values (154, 'Room 1230', 'Sukamaju');
insert into tienda (id_tienda, direccion, ciudad) values (155, 'PO Box 87760', 'Santa Rosa');
insert into tienda (id_tienda, direccion, ciudad) values (156, 'PO Box 57890', 'Miętne');
insert into tienda (id_tienda, direccion, ciudad) values (157, 'Room 1178', 'Cogreg Wetan');
insert into tienda (id_tienda, direccion, ciudad) values (158, 'Room 1784', 'Bogo');
insert into tienda (id_tienda, direccion, ciudad) values (159, 'Apt 1984', 'San Juan');
insert into tienda (id_tienda, direccion, ciudad) values (160, '15th Floor', 'Guayabal');
insert into tienda (id_tienda, direccion, ciudad) values (161, 'PO Box 13678', 'Uhryniv');
insert into tienda (id_tienda, direccion, ciudad) values (162, 'Apt 1283', 'Avarua');
insert into tienda (id_tienda, direccion, ciudad) values (163, '12th Floor', 'Mizur');
insert into tienda (id_tienda, direccion, ciudad) values (164, '1st Floor', 'Mönsterås');
insert into tienda (id_tienda, direccion, ciudad) values (165, 'Apt 1970', 'Putina');
insert into tienda (id_tienda, direccion, ciudad) values (166, 'PO Box 45284', 'Manzini');
insert into tienda (id_tienda, direccion, ciudad) values (167, 'Room 927', 'Marcara');
insert into tienda (id_tienda, direccion, ciudad) values (168, 'Apt 1395', 'Calmar');
insert into tienda (id_tienda, direccion, ciudad) values (169, 'Room 1582', 'Kamiiso');
insert into tienda (id_tienda, direccion, ciudad) values (170, 'PO Box 6449', 'Vykhino-Zhulebino');
insert into tienda (id_tienda, direccion, ciudad) values (171, '9th Floor', 'Bekondo');
insert into tienda (id_tienda, direccion, ciudad) values (172, 'Apt 951', 'Brumadinho');
insert into tienda (id_tienda, direccion, ciudad) values (173, 'Suite 11', 'Bal’shavik');
insert into tienda (id_tienda, direccion, ciudad) values (174, '17th Floor', 'Guanzhuang');
insert into tienda (id_tienda, direccion, ciudad) values (175, 'Suite 60', 'Asyūţ');
insert into tienda (id_tienda, direccion, ciudad) values (176, 'Apt 201', 'Dashiju');
insert into tienda (id_tienda, direccion, ciudad) values (177, 'Suite 87', 'Jayaraga Kaler');
insert into tienda (id_tienda, direccion, ciudad) values (178, '19th Floor', 'Brasília de Minas');
insert into tienda (id_tienda, direccion, ciudad) values (179, 'Suite 3', 'Xinpu');
insert into tienda (id_tienda, direccion, ciudad) values (180, 'Suite 68', 'Soloneshnoye');
insert into tienda (id_tienda, direccion, ciudad) values (181, 'Apt 55', 'Tashkent');
insert into tienda (id_tienda, direccion, ciudad) values (182, 'PO Box 85623', 'Zhangxiang');
insert into tienda (id_tienda, direccion, ciudad) values (183, 'Suite 93', 'Jimenez');
insert into tienda (id_tienda, direccion, ciudad) values (184, 'PO Box 83701', 'Zhexiao');
insert into tienda (id_tienda, direccion, ciudad) values (185, 'Room 1999', 'Tianchang');
insert into tienda (id_tienda, direccion, ciudad) values (186, 'Room 72', 'Buenavista');
insert into tienda (id_tienda, direccion, ciudad) values (187, 'Suite 49', 'Bamban');
insert into tienda (id_tienda, direccion, ciudad) values (188, '4th Floor', 'Estevan');
insert into tienda (id_tienda, direccion, ciudad) values (189, '14th Floor', 'Shicha');
insert into tienda (id_tienda, direccion, ciudad) values (190, 'Suite 52', 'Quimilí');
insert into tienda (id_tienda, direccion, ciudad) values (191, 'Apt 335', 'Tonglin');
insert into tienda (id_tienda, direccion, ciudad) values (192, 'Suite 45', 'Sinacaban');
insert into tienda (id_tienda, direccion, ciudad) values (193, 'Room 1178', 'Temanjang');
insert into tienda (id_tienda, direccion, ciudad) values (194, 'Room 7', 'Jiudu');
insert into tienda (id_tienda, direccion, ciudad) values (195, 'Room 717', 'Zeya');
insert into tienda (id_tienda, direccion, ciudad) values (196, '18th Floor', 'Mohelno');
insert into tienda (id_tienda, direccion, ciudad) values (197, 'Apt 687', 'San Isidro');
insert into tienda (id_tienda, direccion, ciudad) values (198, 'Room 1544', 'Baharly');
insert into tienda (id_tienda, direccion, ciudad) values (199, '4th Floor', 'Huntington');
insert into tienda (id_tienda, direccion, ciudad) values (200, 'PO Box 15954', 'Christchurch');
insert into tienda (id_tienda, direccion, ciudad) values (201, 'PO Box 52435', 'Lebu');
insert into tienda (id_tienda, direccion, ciudad) values (202, 'Suite 41', 'Weishan');
insert into tienda (id_tienda, direccion, ciudad) values (203, 'Suite 32', 'Quintão');
insert into tienda (id_tienda, direccion, ciudad) values (204, 'Apt 90', 'Brodnica');
insert into tienda (id_tienda, direccion, ciudad) values (205, 'Room 327', 'Vila Chã');
insert into tienda (id_tienda, direccion, ciudad) values (206, 'PO Box 66204', 'Las Heras');
insert into tienda (id_tienda, direccion, ciudad) values (207, 'Suite 60', 'Phonsavan');
insert into tienda (id_tienda, direccion, ciudad) values (208, 'Room 1938', 'Oropesa');
insert into tienda (id_tienda, direccion, ciudad) values (209, '12th Floor', 'San Remigio');
insert into tienda (id_tienda, direccion, ciudad) values (210, '20th Floor', 'Bürenhayrhan');
insert into tienda (id_tienda, direccion, ciudad) values (211, 'Apt 682', 'Saint-Julien-en-Genevois');
insert into tienda (id_tienda, direccion, ciudad) values (212, 'Room 991', 'Mīāndoāb');
insert into tienda (id_tienda, direccion, ciudad) values (213, '9th Floor', 'Oefatu');
insert into tienda (id_tienda, direccion, ciudad) values (214, '20th Floor', 'Savannah');
insert into tienda (id_tienda, direccion, ciudad) values (215, 'Suite 87', 'Yanglinshi');
insert into tienda (id_tienda, direccion, ciudad) values (216, '5th Floor', 'Knivsta');
insert into tienda (id_tienda, direccion, ciudad) values (217, '5th Floor', 'Petropavlovsk');
insert into tienda (id_tienda, direccion, ciudad) values (218, 'Room 150', 'Gândara');
insert into tienda (id_tienda, direccion, ciudad) values (219, 'Room 867', 'Jinglongqiao');
insert into tienda (id_tienda, direccion, ciudad) values (220, '6th Floor', 'Istres');
insert into tienda (id_tienda, direccion, ciudad) values (221, 'PO Box 11159', 'Dargaz');
insert into tienda (id_tienda, direccion, ciudad) values (222, 'PO Box 34631', 'Jiangtian');
insert into tienda (id_tienda, direccion, ciudad) values (223, 'Room 23', 'Fengjiang');
insert into tienda (id_tienda, direccion, ciudad) values (224, '19th Floor', 'Mūsa Khel Bāzār');
insert into tienda (id_tienda, direccion, ciudad) values (225, '13th Floor', 'Tanalt');
insert into tienda (id_tienda, direccion, ciudad) values (226, 'Room 1019', 'Nyeri');
insert into tienda (id_tienda, direccion, ciudad) values (227, 'PO Box 56713', 'Alunda');
insert into tienda (id_tienda, direccion, ciudad) values (228, 'Apt 870', 'Pleven');
insert into tienda (id_tienda, direccion, ciudad) values (229, 'Suite 46', 'Synya');
insert into tienda (id_tienda, direccion, ciudad) values (230, 'Apt 735', 'Västerås');
insert into tienda (id_tienda, direccion, ciudad) values (231, 'PO Box 45981', 'Nikolayevskaya');
insert into tienda (id_tienda, direccion, ciudad) values (232, 'Apt 257', 'Hanji');
insert into tienda (id_tienda, direccion, ciudad) values (233, 'Suite 52', 'Melaka');
insert into tienda (id_tienda, direccion, ciudad) values (234, '2nd Floor', 'Dijon');
insert into tienda (id_tienda, direccion, ciudad) values (235, 'Apt 1197', 'Sangallaya');
insert into tienda (id_tienda, direccion, ciudad) values (236, 'Apt 333', 'Zaliznychne');
insert into tienda (id_tienda, direccion, ciudad) values (237, '12th Floor', 'Zhixia');
insert into tienda (id_tienda, direccion, ciudad) values (238, 'Suite 49', 'Yakimovo');
insert into tienda (id_tienda, direccion, ciudad) values (239, 'Apt 552', 'Chuncheon');
insert into tienda (id_tienda, direccion, ciudad) values (240, 'PO Box 76666', 'Kap Choeng');
insert into tienda (id_tienda, direccion, ciudad) values (241, 'Suite 77', 'Al Masallamiyya');
insert into tienda (id_tienda, direccion, ciudad) values (242, 'Apt 991', 'Reszel');
insert into tienda (id_tienda, direccion, ciudad) values (243, 'PO Box 62801', 'Nkayi');
insert into tienda (id_tienda, direccion, ciudad) values (244, 'Apt 379', 'Carodok');
insert into tienda (id_tienda, direccion, ciudad) values (245, '15th Floor', 'Kahabe');
insert into tienda (id_tienda, direccion, ciudad) values (246, 'Apt 1239', 'Changdai');
insert into tienda (id_tienda, direccion, ciudad) values (247, 'PO Box 3315', 'Shuangbaiyang');
insert into tienda (id_tienda, direccion, ciudad) values (248, 'PO Box 12082', 'Batanovtsi');
insert into tienda (id_tienda, direccion, ciudad) values (249, 'PO Box 93664', 'Dan Makham Tia');
insert into tienda (id_tienda, direccion, ciudad) values (250, 'PO Box 63568', 'Shuangshan');
insert into tienda (id_tienda, direccion, ciudad) values (251, '6th Floor', 'Numazu');
insert into tienda (id_tienda, direccion, ciudad) values (252, 'Apt 537', 'Zaragoza');
insert into tienda (id_tienda, direccion, ciudad) values (253, 'Suite 64', 'Nihaona');
insert into tienda (id_tienda, direccion, ciudad) values (254, '18th Floor', 'West Palm Beach');
insert into tienda (id_tienda, direccion, ciudad) values (255, 'Room 167', 'Changtang');
insert into tienda (id_tienda, direccion, ciudad) values (256, 'Apt 864', 'Leipzig');
insert into tienda (id_tienda, direccion, ciudad) values (257, 'Apt 247', 'Novki');
insert into tienda (id_tienda, direccion, ciudad) values (258, 'PO Box 52971', 'Babana');
insert into tienda (id_tienda, direccion, ciudad) values (259, 'Room 527', 'Pniv');
insert into tienda (id_tienda, direccion, ciudad) values (260, 'PO Box 39672', 'Lavradio');
insert into tienda (id_tienda, direccion, ciudad) values (261, '18th Floor', 'Chiquinquirá');
insert into tienda (id_tienda, direccion, ciudad) values (262, 'Apt 1163', 'North Shore');
insert into tienda (id_tienda, direccion, ciudad) values (263, 'Room 1571', 'Xiangtan');
insert into tienda (id_tienda, direccion, ciudad) values (264, '17th Floor', 'Şabbūrah');
insert into tienda (id_tienda, direccion, ciudad) values (265, 'Room 393', 'Sigou');
insert into tienda (id_tienda, direccion, ciudad) values (266, '13th Floor', 'Rosh Pinna');
insert into tienda (id_tienda, direccion, ciudad) values (267, '7th Floor', 'Karangtawar');
insert into tienda (id_tienda, direccion, ciudad) values (268, 'Room 101', 'Kota Kinabalu');
insert into tienda (id_tienda, direccion, ciudad) values (269, 'Suite 99', 'Jinjing');
insert into tienda (id_tienda, direccion, ciudad) values (270, 'Apt 366', 'Yaojiagou');
insert into tienda (id_tienda, direccion, ciudad) values (271, 'Apt 654', 'Youghal');
insert into tienda (id_tienda, direccion, ciudad) values (272, '4th Floor', 'Sishui');
insert into tienda (id_tienda, direccion, ciudad) values (273, 'Room 1411', 'Mangxing');
insert into tienda (id_tienda, direccion, ciudad) values (274, 'Apt 1382', 'Ono');
insert into tienda (id_tienda, direccion, ciudad) values (275, '10th Floor', 'Tabango');
insert into tienda (id_tienda, direccion, ciudad) values (276, 'Apt 2', 'Mooka');
insert into tienda (id_tienda, direccion, ciudad) values (277, '4th Floor', 'Kaduseeng');
insert into tienda (id_tienda, direccion, ciudad) values (278, 'PO Box 18395', 'Corzuela');
insert into tienda (id_tienda, direccion, ciudad) values (279, '19th Floor', 'Teberda');
insert into tienda (id_tienda, direccion, ciudad) values (280, 'Room 1944', 'Heemstede');
insert into tienda (id_tienda, direccion, ciudad) values (281, 'Room 391', 'Tianxin');
insert into tienda (id_tienda, direccion, ciudad) values (282, 'Apt 146', 'Niuzhuang');
insert into tienda (id_tienda, direccion, ciudad) values (283, 'Suite 76', 'La Hacienda');
insert into tienda (id_tienda, direccion, ciudad) values (284, '6th Floor', 'Hankasalmi');
insert into tienda (id_tienda, direccion, ciudad) values (285, 'Suite 89', 'Rasūlnagar');
insert into tienda (id_tienda, direccion, ciudad) values (286, 'PO Box 26441', 'Prabuty');
insert into tienda (id_tienda, direccion, ciudad) values (287, '17th Floor', 'Kärdla');
insert into tienda (id_tienda, direccion, ciudad) values (288, 'Apt 956', 'Chengbei');
insert into tienda (id_tienda, direccion, ciudad) values (289, 'Apt 716', 'Kunwi');
insert into tienda (id_tienda, direccion, ciudad) values (290, '14th Floor', 'Mora');
insert into tienda (id_tienda, direccion, ciudad) values (291, 'Apt 1932', 'Merlo');
insert into tienda (id_tienda, direccion, ciudad) values (292, 'Suite 7', 'Hengjian');
insert into tienda (id_tienda, direccion, ciudad) values (293, 'PO Box 92314', 'Kasukabe');
insert into tienda (id_tienda, direccion, ciudad) values (294, 'PO Box 2458', 'Obsza');
insert into tienda (id_tienda, direccion, ciudad) values (295, 'PO Box 10574', 'Bayt Wazan');
insert into tienda (id_tienda, direccion, ciudad) values (296, 'PO Box 2614', 'Napoles');
insert into tienda (id_tienda, direccion, ciudad) values (297, 'Apt 553', 'Karlovo');
insert into tienda (id_tienda, direccion, ciudad) values (298, 'Suite 73', 'Shakīso');
insert into tienda (id_tienda, direccion, ciudad) values (299, 'PO Box 1996', 'Adela');
insert into tienda (id_tienda, direccion, ciudad) values (300, '18th Floor', 'Anhua');
insert into tienda (id_tienda, direccion, ciudad) values (301, 'Apt 73', 'Huoli');
insert into tienda (id_tienda, direccion, ciudad) values (302, 'Room 855', 'Gálvez');
insert into tienda (id_tienda, direccion, ciudad) values (303, 'Suite 79', 'Khairpur Nathan Shāh');
insert into tienda (id_tienda, direccion, ciudad) values (304, 'Room 283', 'Xietang');
insert into tienda (id_tienda, direccion, ciudad) values (305, 'Suite 52', 'Santa Maria');
insert into tienda (id_tienda, direccion, ciudad) values (306, 'Room 1505', 'Tisno');
insert into tienda (id_tienda, direccion, ciudad) values (307, 'Room 174', 'Fuchūchō');
insert into tienda (id_tienda, direccion, ciudad) values (308, '6th Floor', 'Xiaoruo');
insert into tienda (id_tienda, direccion, ciudad) values (309, 'Apt 692', 'Kimhae');
insert into tienda (id_tienda, direccion, ciudad) values (310, '3rd Floor', 'Mbale');
insert into tienda (id_tienda, direccion, ciudad) values (311, 'Room 1553', 'Mudanjiang');
insert into tienda (id_tienda, direccion, ciudad) values (312, 'Suite 91', 'Topeka');
insert into tienda (id_tienda, direccion, ciudad) values (313, '8th Floor', 'Bang Kaeo');
insert into tienda (id_tienda, direccion, ciudad) values (314, '15th Floor', 'Bochum');
insert into tienda (id_tienda, direccion, ciudad) values (315, 'Room 1139', 'Batu');
insert into tienda (id_tienda, direccion, ciudad) values (316, 'PO Box 43857', 'Frederiksberg');
insert into tienda (id_tienda, direccion, ciudad) values (317, 'Suite 2', 'Smimou');
insert into tienda (id_tienda, direccion, ciudad) values (318, 'Apt 1693', 'Campos Belos');
insert into tienda (id_tienda, direccion, ciudad) values (319, '5th Floor', 'Chrast');
insert into tienda (id_tienda, direccion, ciudad) values (320, 'Room 1462', 'Purbalingga');
insert into tienda (id_tienda, direccion, ciudad) values (321, 'Suite 10', 'Belmullet');
insert into tienda (id_tienda, direccion, ciudad) values (322, 'Apt 1863', 'Grzechynia');
insert into tienda (id_tienda, direccion, ciudad) values (323, 'Room 1588', 'Darya Boyi');
insert into tienda (id_tienda, direccion, ciudad) values (324, 'Suite 100', 'Alor Setar');
insert into tienda (id_tienda, direccion, ciudad) values (325, 'Room 803', 'Jingkou');
insert into tienda (id_tienda, direccion, ciudad) values (326, 'Apt 595', 'Hengshui');
insert into tienda (id_tienda, direccion, ciudad) values (327, 'PO Box 1173', 'Zhongben');
insert into tienda (id_tienda, direccion, ciudad) values (328, 'Apt 471', 'Xujia');
insert into tienda (id_tienda, direccion, ciudad) values (329, 'Suite 93', 'Seda');
insert into tienda (id_tienda, direccion, ciudad) values (330, 'PO Box 44519', 'Stanišić');
insert into tienda (id_tienda, direccion, ciudad) values (331, '10th Floor', 'Jacareí');
insert into tienda (id_tienda, direccion, ciudad) values (332, 'PO Box 93375', 'Mniszków');
insert into tienda (id_tienda, direccion, ciudad) values (333, '6th Floor', 'Huancarqui');
insert into tienda (id_tienda, direccion, ciudad) values (334, 'PO Box 68012', 'La Romana');
insert into tienda (id_tienda, direccion, ciudad) values (335, '11th Floor', 'Liboro');
insert into tienda (id_tienda, direccion, ciudad) values (336, 'Suite 95', 'Isla Pucú');
insert into tienda (id_tienda, direccion, ciudad) values (337, 'Suite 75', 'Buffalo');
insert into tienda (id_tienda, direccion, ciudad) values (338, 'Room 300', 'Hetoudian');
insert into tienda (id_tienda, direccion, ciudad) values (339, 'PO Box 59756', 'Sémbé');
insert into tienda (id_tienda, direccion, ciudad) values (340, 'Suite 3', 'Baiyang');
insert into tienda (id_tienda, direccion, ciudad) values (341, 'PO Box 61587', 'San Narciso');
insert into tienda (id_tienda, direccion, ciudad) values (342, '16th Floor', 'Kičevo');
insert into tienda (id_tienda, direccion, ciudad) values (343, 'Room 1802', 'Wewit');
insert into tienda (id_tienda, direccion, ciudad) values (344, 'Apt 974', 'Baojia');
insert into tienda (id_tienda, direccion, ciudad) values (345, 'Suite 30', 'Kayar');
insert into tienda (id_tienda, direccion, ciudad) values (346, 'Suite 31', 'Majzar');
insert into tienda (id_tienda, direccion, ciudad) values (347, 'Suite 51', 'Al Hufūf');
insert into tienda (id_tienda, direccion, ciudad) values (348, 'Room 852', 'Zimmi');
insert into tienda (id_tienda, direccion, ciudad) values (349, 'Suite 82', 'Salvador');
insert into tienda (id_tienda, direccion, ciudad) values (350, 'PO Box 65475', 'Caicedonia');
insert into tienda (id_tienda, direccion, ciudad) values (351, '11th Floor', 'Verkhozim');
insert into tienda (id_tienda, direccion, ciudad) values (352, 'PO Box 64213', 'Bundoran');
insert into tienda (id_tienda, direccion, ciudad) values (353, 'Room 526', 'Bromma');
insert into tienda (id_tienda, direccion, ciudad) values (354, 'PO Box 8589', 'Xitou');
insert into tienda (id_tienda, direccion, ciudad) values (355, 'PO Box 67241', 'Qabaqçöl');
insert into tienda (id_tienda, direccion, ciudad) values (356, 'Suite 48', 'Krzczonów');
insert into tienda (id_tienda, direccion, ciudad) values (357, '11th Floor', 'Minanga Norte');
insert into tienda (id_tienda, direccion, ciudad) values (358, 'Suite 18', 'Widorokandang');
insert into tienda (id_tienda, direccion, ciudad) values (359, 'Room 91', 'Salcedo');
insert into tienda (id_tienda, direccion, ciudad) values (360, 'Apt 1680', 'Szeged');
insert into tienda (id_tienda, direccion, ciudad) values (361, '1st Floor', 'Huangzhan');
insert into tienda (id_tienda, direccion, ciudad) values (362, 'PO Box 32016', 'Bejuco');
insert into tienda (id_tienda, direccion, ciudad) values (363, 'Room 188', 'Toulouse');
insert into tienda (id_tienda, direccion, ciudad) values (364, 'Suite 51', 'Melati');
insert into tienda (id_tienda, direccion, ciudad) values (365, 'Suite 70', 'Seara');
insert into tienda (id_tienda, direccion, ciudad) values (366, 'PO Box 15952', 'Lgota Wielka');
insert into tienda (id_tienda, direccion, ciudad) values (367, 'PO Box 21049', 'Mengeš');
insert into tienda (id_tienda, direccion, ciudad) values (368, 'Room 1851', 'Duitama');
insert into tienda (id_tienda, direccion, ciudad) values (369, 'PO Box 24124', 'Preko');
insert into tienda (id_tienda, direccion, ciudad) values (370, 'Room 700', 'Lincoln');
insert into tienda (id_tienda, direccion, ciudad) values (371, 'Suite 56', 'Sundsvall');
insert into tienda (id_tienda, direccion, ciudad) values (372, 'Apt 1088', 'Jimo');
insert into tienda (id_tienda, direccion, ciudad) values (373, 'Suite 17', 'Lexington');
insert into tienda (id_tienda, direccion, ciudad) values (374, '12th Floor', 'Pilawa');
insert into tienda (id_tienda, direccion, ciudad) values (375, 'Apt 916', 'Estevan');
insert into tienda (id_tienda, direccion, ciudad) values (376, 'Room 1749', 'Mananjary');
insert into tienda (id_tienda, direccion, ciudad) values (377, 'Suite 59', 'Kanginan');
insert into tienda (id_tienda, direccion, ciudad) values (378, 'Apt 717', 'Huangwei');
insert into tienda (id_tienda, direccion, ciudad) values (379, 'Room 1848', 'Xinshi');
insert into tienda (id_tienda, direccion, ciudad) values (380, 'Apt 1025', 'Pau');
insert into tienda (id_tienda, direccion, ciudad) values (381, 'PO Box 64848', 'Krayen');
insert into tienda (id_tienda, direccion, ciudad) values (382, '7th Floor', 'Mantampay');
insert into tienda (id_tienda, direccion, ciudad) values (383, 'Apt 1853', 'Baklashi');
insert into tienda (id_tienda, direccion, ciudad) values (384, '11th Floor', 'Sunzhuang');
insert into tienda (id_tienda, direccion, ciudad) values (385, 'Suite 79', 'Kusak');
insert into tienda (id_tienda, direccion, ciudad) values (386, '18th Floor', 'Rufino');
insert into tienda (id_tienda, direccion, ciudad) values (387, '15th Floor', 'Los Nogales');
insert into tienda (id_tienda, direccion, ciudad) values (388, '4th Floor', 'Qingkenpao');
insert into tienda (id_tienda, direccion, ciudad) values (389, '13th Floor', 'Kinalansan');
insert into tienda (id_tienda, direccion, ciudad) values (390, '20th Floor', 'Rutul');
insert into tienda (id_tienda, direccion, ciudad) values (391, 'Suite 32', 'Koshigaya');
insert into tienda (id_tienda, direccion, ciudad) values (392, 'Suite 79', 'Lemende');
insert into tienda (id_tienda, direccion, ciudad) values (393, 'PO Box 44449', 'Smarhon’');
insert into tienda (id_tienda, direccion, ciudad) values (394, 'Room 1846', 'Býšť');
insert into tienda (id_tienda, direccion, ciudad) values (395, '7th Floor', 'Kuala Tuha');
insert into tienda (id_tienda, direccion, ciudad) values (396, '11th Floor', 'Aviúges');
insert into tienda (id_tienda, direccion, ciudad) values (397, 'Apt 608', 'Panambi');
insert into tienda (id_tienda, direccion, ciudad) values (398, 'PO Box 75810', 'Mataguži');
insert into tienda (id_tienda, direccion, ciudad) values (399, 'Room 540', 'Pasadena');
insert into tienda (id_tienda, direccion, ciudad) values (400, 'PO Box 14706', 'Banjaranyar');
insert into tienda (id_tienda, direccion, ciudad) values (401, 'Apt 1091', 'Yuanqiao');
insert into tienda (id_tienda, direccion, ciudad) values (402, 'PO Box 95627', 'Sarāb');
insert into tienda (id_tienda, direccion, ciudad) values (403, 'Suite 82', 'Dalakovo');
insert into tienda (id_tienda, direccion, ciudad) values (404, 'Suite 57', 'Guisser');
insert into tienda (id_tienda, direccion, ciudad) values (405, 'Room 1718', 'Tver');
insert into tienda (id_tienda, direccion, ciudad) values (406, '20th Floor', 'Cabinda');
insert into tienda (id_tienda, direccion, ciudad) values (407, 'Apt 993', 'Rosh Ha‘Ayin');
insert into tienda (id_tienda, direccion, ciudad) values (408, '12th Floor', 'Campinho');
insert into tienda (id_tienda, direccion, ciudad) values (409, 'Suite 35', 'Paris 14');
insert into tienda (id_tienda, direccion, ciudad) values (410, 'Room 884', 'Namysłów');
insert into tienda (id_tienda, direccion, ciudad) values (411, 'Apt 617', 'Corcuera');
insert into tienda (id_tienda, direccion, ciudad) values (412, 'PO Box 37479', 'Quimilí');
insert into tienda (id_tienda, direccion, ciudad) values (413, '8th Floor', 'La Chapelle-sur-Erdre');
insert into tienda (id_tienda, direccion, ciudad) values (414, 'PO Box 27048', 'Nîmes');
insert into tienda (id_tienda, direccion, ciudad) values (415, '3rd Floor', 'Jinrui');
insert into tienda (id_tienda, direccion, ciudad) values (416, 'PO Box 30827', 'Shilong');
insert into tienda (id_tienda, direccion, ciudad) values (417, '14th Floor', 'Radlje ob Dravi');
insert into tienda (id_tienda, direccion, ciudad) values (418, 'Suite 35', 'Kadubadak');
insert into tienda (id_tienda, direccion, ciudad) values (419, 'Room 273', 'Hanji');
insert into tienda (id_tienda, direccion, ciudad) values (420, 'Room 1156', 'Lasehao');
insert into tienda (id_tienda, direccion, ciudad) values (421, 'Apt 1429', 'Songlong');
insert into tienda (id_tienda, direccion, ciudad) values (422, '4th Floor', 'Lishu');
insert into tienda (id_tienda, direccion, ciudad) values (423, '16th Floor', 'Nahāvand');
insert into tienda (id_tienda, direccion, ciudad) values (424, 'Suite 7', 'Goragorskiy');
insert into tienda (id_tienda, direccion, ciudad) values (425, 'Apt 103', 'Gränna');
insert into tienda (id_tienda, direccion, ciudad) values (426, 'PO Box 69037', 'Cuyotenango');
insert into tienda (id_tienda, direccion, ciudad) values (427, 'PO Box 6263', 'Guashe');
insert into tienda (id_tienda, direccion, ciudad) values (428, '17th Floor', 'Shangjie');
insert into tienda (id_tienda, direccion, ciudad) values (429, 'Apt 1407', 'Las Palmas');
insert into tienda (id_tienda, direccion, ciudad) values (430, '15th Floor', 'Dharān Bāzār');
insert into tienda (id_tienda, direccion, ciudad) values (431, 'PO Box 88895', 'Sukhobezvodnoye');
insert into tienda (id_tienda, direccion, ciudad) values (432, 'Apt 1870', 'Oxelösund');
insert into tienda (id_tienda, direccion, ciudad) values (433, 'PO Box 883', 'Azurva');
insert into tienda (id_tienda, direccion, ciudad) values (434, 'PO Box 35438', 'Terter');
insert into tienda (id_tienda, direccion, ciudad) values (435, 'Room 1570', 'Rivesaltes');
insert into tienda (id_tienda, direccion, ciudad) values (436, 'Apt 966', 'Kapyl’');
insert into tienda (id_tienda, direccion, ciudad) values (437, 'Room 954', 'Livramento do Brumado');
insert into tienda (id_tienda, direccion, ciudad) values (438, 'Apt 1081', 'Waina');
insert into tienda (id_tienda, direccion, ciudad) values (439, '16th Floor', 'Johanneshov');
insert into tienda (id_tienda, direccion, ciudad) values (440, 'Suite 66', 'Plettenberg Bay');
insert into tienda (id_tienda, direccion, ciudad) values (441, 'PO Box 14444', 'Novomoskovsk');
insert into tienda (id_tienda, direccion, ciudad) values (442, 'Room 389', 'Kotkot');
insert into tienda (id_tienda, direccion, ciudad) values (443, 'Apt 413', 'Cahors');
insert into tienda (id_tienda, direccion, ciudad) values (444, 'Suite 17', 'Mestre');
insert into tienda (id_tienda, direccion, ciudad) values (445, 'Room 463', 'Moyo');
insert into tienda (id_tienda, direccion, ciudad) values (446, 'Suite 8', 'Kupusina');
insert into tienda (id_tienda, direccion, ciudad) values (447, 'Room 513', 'Victoria Falls');
insert into tienda (id_tienda, direccion, ciudad) values (448, 'Room 1233', 'Ciudad Ojeda');
insert into tienda (id_tienda, direccion, ciudad) values (449, 'Suite 84', 'Kiangan');
insert into tienda (id_tienda, direccion, ciudad) values (450, '1st Floor', 'Pajeksan');
insert into tienda (id_tienda, direccion, ciudad) values (451, 'Suite 92', 'Zlaté Hory');
insert into tienda (id_tienda, direccion, ciudad) values (452, 'Room 1218', 'New York City');
insert into tienda (id_tienda, direccion, ciudad) values (453, 'Suite 31', 'Sydney');
insert into tienda (id_tienda, direccion, ciudad) values (454, 'Apt 1882', 'Banī an Nahārī');
insert into tienda (id_tienda, direccion, ciudad) values (455, 'Room 1962', 'Kamenka');
insert into tienda (id_tienda, direccion, ciudad) values (456, 'PO Box 32685', 'Strezhevoy');
insert into tienda (id_tienda, direccion, ciudad) values (457, 'Room 1749', 'Gaoliang');
insert into tienda (id_tienda, direccion, ciudad) values (458, 'Apt 302', 'Babakanlapang');
insert into tienda (id_tienda, direccion, ciudad) values (459, '7th Floor', 'Lianshan');
insert into tienda (id_tienda, direccion, ciudad) values (460, 'Suite 10', 'Vereshchagino');
insert into tienda (id_tienda, direccion, ciudad) values (461, 'Suite 36', 'Bāqim as Sūq');
insert into tienda (id_tienda, direccion, ciudad) values (462, '10th Floor', 'Ts’khinvali');
insert into tienda (id_tienda, direccion, ciudad) values (463, 'PO Box 69801', 'Oberá');
insert into tienda (id_tienda, direccion, ciudad) values (464, 'Apt 121', 'Tsuen Wan');
insert into tienda (id_tienda, direccion, ciudad) values (465, 'Room 779', 'Gyōda');
insert into tienda (id_tienda, direccion, ciudad) values (466, 'PO Box 22342', 'Fangjun');
insert into tienda (id_tienda, direccion, ciudad) values (467, 'Apt 462', 'Kavār');
insert into tienda (id_tienda, direccion, ciudad) values (468, 'Room 1396', 'Cikandang');
insert into tienda (id_tienda, direccion, ciudad) values (469, '15th Floor', 'Dmitriyevskoye');
insert into tienda (id_tienda, direccion, ciudad) values (470, 'Room 218', 'Talipan');
insert into tienda (id_tienda, direccion, ciudad) values (471, 'PO Box 38524', 'Koropí');
insert into tienda (id_tienda, direccion, ciudad) values (472, 'Suite 90', 'Zhuhu');
insert into tienda (id_tienda, direccion, ciudad) values (473, 'Apt 959', 'Tangyu');
insert into tienda (id_tienda, direccion, ciudad) values (474, 'PO Box 23054', 'Dongyuan');
insert into tienda (id_tienda, direccion, ciudad) values (475, 'Suite 70', 'Ji’an');
insert into tienda (id_tienda, direccion, ciudad) values (476, '20th Floor', 'La Rochelle');
insert into tienda (id_tienda, direccion, ciudad) values (477, '8th Floor', 'Fatuulan');
insert into tienda (id_tienda, direccion, ciudad) values (478, 'Apt 1388', 'Weitang');
insert into tienda (id_tienda, direccion, ciudad) values (479, 'Suite 73', 'Damai');
insert into tienda (id_tienda, direccion, ciudad) values (480, 'Suite 95', 'Al Fashn');
insert into tienda (id_tienda, direccion, ciudad) values (481, 'Room 320', 'Sinarjaya');
insert into tienda (id_tienda, direccion, ciudad) values (482, 'Apt 650', 'Toulouse');
insert into tienda (id_tienda, direccion, ciudad) values (483, 'Room 498', 'Sumbersari Wetan');
insert into tienda (id_tienda, direccion, ciudad) values (484, 'Room 1759', 'Tirlyanskiy');
insert into tienda (id_tienda, direccion, ciudad) values (485, '10th Floor', 'Kálymnos');
insert into tienda (id_tienda, direccion, ciudad) values (486, 'Suite 99', 'Orikum');
insert into tienda (id_tienda, direccion, ciudad) values (487, 'PO Box 17922', 'Klayusiwalan');
insert into tienda (id_tienda, direccion, ciudad) values (488, 'PO Box 37436', 'Mislak');
insert into tienda (id_tienda, direccion, ciudad) values (489, 'Room 1073', 'Beringin');
insert into tienda (id_tienda, direccion, ciudad) values (490, 'Apt 207', 'Xinzhan');
insert into tienda (id_tienda, direccion, ciudad) values (491, 'Apt 1068', 'Hepingyizu');
insert into tienda (id_tienda, direccion, ciudad) values (492, 'PO Box 56515', 'Shanghang');
insert into tienda (id_tienda, direccion, ciudad) values (493, 'Apt 617', 'Were Īlu');
insert into tienda (id_tienda, direccion, ciudad) values (494, 'Suite 98', 'Echarate');
insert into tienda (id_tienda, direccion, ciudad) values (495, 'Suite 32', 'Mutā Khān');
insert into tienda (id_tienda, direccion, ciudad) values (496, '13th Floor', 'Taisen-ri');
insert into tienda (id_tienda, direccion, ciudad) values (497, 'Suite 12', 'Leuwihalang');
insert into tienda (id_tienda, direccion, ciudad) values (498, 'Suite 79', 'Beijiang');
insert into tienda (id_tienda, direccion, ciudad) values (499, 'Room 1890', 'Buang');
insert into tienda (id_tienda, direccion, ciudad) values (500, 'Room 634', 'Beauvais');
insert into tienda (id_tienda, direccion, ciudad) values (501, 'Apt 1890', 'Independencia');
insert into tienda (id_tienda, direccion, ciudad) values (502, 'Apt 693', 'Barra Mansa');
insert into tienda (id_tienda, direccion, ciudad) values (503, 'PO Box 52703', 'Detik Satu');
insert into tienda (id_tienda, direccion, ciudad) values (504, 'Room 571', 'Dili');
insert into tienda (id_tienda, direccion, ciudad) values (505, '15th Floor', 'Curahnongko');
insert into tienda (id_tienda, direccion, ciudad) values (506, 'PO Box 10643', 'Amparita');
insert into tienda (id_tienda, direccion, ciudad) values (507, 'Room 1455', 'Flores da Cunha');
insert into tienda (id_tienda, direccion, ciudad) values (508, 'PO Box 60602', 'Julcamarca');
insert into tienda (id_tienda, direccion, ciudad) values (509, '19th Floor', 'Bhalwāl');
insert into tienda (id_tienda, direccion, ciudad) values (510, 'Suite 26', 'Río Grande');
insert into tienda (id_tienda, direccion, ciudad) values (511, 'Room 1360', 'Roun Satu');
insert into tienda (id_tienda, direccion, ciudad) values (512, '8th Floor', 'Borek');
insert into tienda (id_tienda, direccion, ciudad) values (513, 'Suite 33', 'Malakhovka');
insert into tienda (id_tienda, direccion, ciudad) values (514, '9th Floor', 'Nakhon Pathom');
insert into tienda (id_tienda, direccion, ciudad) values (515, 'Apt 1130', 'Prnjavor');
insert into tienda (id_tienda, direccion, ciudad) values (516, 'Suite 60', 'Luxi');
insert into tienda (id_tienda, direccion, ciudad) values (517, '18th Floor', 'Gandrungmangu');
insert into tienda (id_tienda, direccion, ciudad) values (518, '12th Floor', 'Krajanjugosari');
insert into tienda (id_tienda, direccion, ciudad) values (519, 'Room 74', 'Pīr jo Goth');
insert into tienda (id_tienda, direccion, ciudad) values (520, 'Room 1184', 'Riyadh');
insert into tienda (id_tienda, direccion, ciudad) values (521, 'Apt 77', 'Ash Shuhadā’');
insert into tienda (id_tienda, direccion, ciudad) values (522, 'Apt 521', 'Jetak');
insert into tienda (id_tienda, direccion, ciudad) values (523, 'Room 1379', 'Chengzhai');
insert into tienda (id_tienda, direccion, ciudad) values (524, 'Suite 61', 'Mīrābād');
insert into tienda (id_tienda, direccion, ciudad) values (525, 'Apt 439', 'Kéfalos');
insert into tienda (id_tienda, direccion, ciudad) values (526, 'Apt 1074', 'Perth');
insert into tienda (id_tienda, direccion, ciudad) values (527, 'Apt 909', 'Cavadas');
insert into tienda (id_tienda, direccion, ciudad) values (528, 'PO Box 62495', 'Chavarría');
insert into tienda (id_tienda, direccion, ciudad) values (529, 'Suite 72', 'Ciudad Choluteca');
insert into tienda (id_tienda, direccion, ciudad) values (530, 'Apt 460', 'Shuanghe');
insert into tienda (id_tienda, direccion, ciudad) values (531, 'Suite 13', 'Shurugwi');
insert into tienda (id_tienda, direccion, ciudad) values (532, 'Apt 1950', 'Miyata');
insert into tienda (id_tienda, direccion, ciudad) values (533, '19th Floor', 'Abnūb');
insert into tienda (id_tienda, direccion, ciudad) values (534, 'Room 1370', 'Sagbayan');
insert into tienda (id_tienda, direccion, ciudad) values (535, '1st Floor', 'Tyczyn');
insert into tienda (id_tienda, direccion, ciudad) values (536, 'Apt 1095', 'Delvinë');
insert into tienda (id_tienda, direccion, ciudad) values (537, 'PO Box 98371', 'Pale');
insert into tienda (id_tienda, direccion, ciudad) values (538, 'Apt 922', 'Vikhorevka');
insert into tienda (id_tienda, direccion, ciudad) values (539, 'Room 1732', 'Niushou');
insert into tienda (id_tienda, direccion, ciudad) values (540, 'PO Box 86296', 'Changping');
insert into tienda (id_tienda, direccion, ciudad) values (541, 'Suite 36', 'Huité');
insert into tienda (id_tienda, direccion, ciudad) values (542, 'Suite 76', 'Dongtundu');
insert into tienda (id_tienda, direccion, ciudad) values (543, '10th Floor', 'Velykyy Burluk');
insert into tienda (id_tienda, direccion, ciudad) values (544, '7th Floor', 'Qibu');
insert into tienda (id_tienda, direccion, ciudad) values (545, 'Apt 1734', 'Malasiqui');
insert into tienda (id_tienda, direccion, ciudad) values (546, 'Suite 71', 'Acul du Nord');
insert into tienda (id_tienda, direccion, ciudad) values (547, '3rd Floor', 'Matviyivka');
insert into tienda (id_tienda, direccion, ciudad) values (548, 'Room 200', 'Chaviña');
insert into tienda (id_tienda, direccion, ciudad) values (549, 'Suite 21', 'Ila Orangun');
insert into tienda (id_tienda, direccion, ciudad) values (550, 'Room 176', 'Likwatang Timur');
insert into tienda (id_tienda, direccion, ciudad) values (551, 'Suite 46', 'Puerto Rico');
insert into tienda (id_tienda, direccion, ciudad) values (552, 'Apt 342', 'Jinqu');
insert into tienda (id_tienda, direccion, ciudad) values (553, '4th Floor', 'Lloqan');
insert into tienda (id_tienda, direccion, ciudad) values (554, 'Suite 51', 'Odiongan');
insert into tienda (id_tienda, direccion, ciudad) values (555, 'Suite 54', 'Artémida');
insert into tienda (id_tienda, direccion, ciudad) values (556, 'Room 897', 'Bilopillya');
insert into tienda (id_tienda, direccion, ciudad) values (557, '10th Floor', 'Sinubong');
insert into tienda (id_tienda, direccion, ciudad) values (558, 'PO Box 88502', 'Pedra Azul');
insert into tienda (id_tienda, direccion, ciudad) values (559, 'Suite 65', 'Lishan');
insert into tienda (id_tienda, direccion, ciudad) values (560, 'PO Box 47166', 'Głogów Małopolski');
insert into tienda (id_tienda, direccion, ciudad) values (561, 'PO Box 2236', 'Seremban');
insert into tienda (id_tienda, direccion, ciudad) values (562, '11th Floor', 'Pa Tio');
insert into tienda (id_tienda, direccion, ciudad) values (563, '4th Floor', 'Banjar Timbrah');
insert into tienda (id_tienda, direccion, ciudad) values (564, 'Apt 1595', 'Xufu');
insert into tienda (id_tienda, direccion, ciudad) values (565, '4th Floor', 'Hedian');
insert into tienda (id_tienda, direccion, ciudad) values (566, 'Apt 779', 'Alhambra');
insert into tienda (id_tienda, direccion, ciudad) values (567, 'Room 1082', 'Gadon');
insert into tienda (id_tienda, direccion, ciudad) values (568, 'Room 998', 'Muslyumovo');
insert into tienda (id_tienda, direccion, ciudad) values (569, 'Suite 85', 'Juradó');
insert into tienda (id_tienda, direccion, ciudad) values (570, 'Apt 1503', 'Zagórów');
insert into tienda (id_tienda, direccion, ciudad) values (571, 'Suite 33', 'Busilak');
insert into tienda (id_tienda, direccion, ciudad) values (572, '6th Floor', 'Onueke');
insert into tienda (id_tienda, direccion, ciudad) values (573, 'Apt 1609', 'Nueva Ocotepeque');
insert into tienda (id_tienda, direccion, ciudad) values (574, 'Apt 1075', 'Podwilk');
insert into tienda (id_tienda, direccion, ciudad) values (575, 'Room 1646', 'Jibiya');
insert into tienda (id_tienda, direccion, ciudad) values (576, '5th Floor', 'Yuantan');
insert into tienda (id_tienda, direccion, ciudad) values (577, 'PO Box 63452', 'Tagbina');
insert into tienda (id_tienda, direccion, ciudad) values (578, '10th Floor', 'Camachile');
insert into tienda (id_tienda, direccion, ciudad) values (579, 'Suite 4', 'Pontang Tengah');
insert into tienda (id_tienda, direccion, ciudad) values (580, 'PO Box 52988', 'Aubagne');
insert into tienda (id_tienda, direccion, ciudad) values (581, '14th Floor', 'Şuraabad');
insert into tienda (id_tienda, direccion, ciudad) values (582, '6th Floor', 'Kingston');
insert into tienda (id_tienda, direccion, ciudad) values (583, '3rd Floor', 'Le Pontet');
insert into tienda (id_tienda, direccion, ciudad) values (584, '15th Floor', 'Los Angeles');
insert into tienda (id_tienda, direccion, ciudad) values (585, '5th Floor', 'Spas’ke');
insert into tienda (id_tienda, direccion, ciudad) values (586, 'Suite 85', 'Huyuan');
insert into tienda (id_tienda, direccion, ciudad) values (587, 'PO Box 66970', 'Zakroczym');
insert into tienda (id_tienda, direccion, ciudad) values (588, 'Suite 42', 'Catarman');
insert into tienda (id_tienda, direccion, ciudad) values (589, '12th Floor', 'Kota Kinabalu');
insert into tienda (id_tienda, direccion, ciudad) values (590, 'Room 1878', 'Krajan Timur Mlokorejo');
insert into tienda (id_tienda, direccion, ciudad) values (591, 'Suite 69', 'Saint-Maurice');
insert into tienda (id_tienda, direccion, ciudad) values (592, 'Apt 593', 'Changtang');
insert into tienda (id_tienda, direccion, ciudad) values (593, '3rd Floor', 'Gaoshi');
insert into tienda (id_tienda, direccion, ciudad) values (594, 'Room 623', 'Photharam');
insert into tienda (id_tienda, direccion, ciudad) values (595, 'PO Box 86045', 'Furudate');
insert into tienda (id_tienda, direccion, ciudad) values (596, 'PO Box 28159', 'Sölvesborg');
insert into tienda (id_tienda, direccion, ciudad) values (597, 'Room 126', 'Oslo');
insert into tienda (id_tienda, direccion, ciudad) values (598, 'Room 514', 'Jirkov');
insert into tienda (id_tienda, direccion, ciudad) values (599, '20th Floor', 'Pedinó');
insert into tienda (id_tienda, direccion, ciudad) values (600, '6th Floor', 'Sypniewo');
insert into tienda (id_tienda, direccion, ciudad) values (601, '3rd Floor', 'Potchefstroom');
insert into tienda (id_tienda, direccion, ciudad) values (602, '15th Floor', 'Daliyuan');
insert into tienda (id_tienda, direccion, ciudad) values (603, 'Suite 33', 'Thị Trấn Cẩm Thủy');
insert into tienda (id_tienda, direccion, ciudad) values (604, '18th Floor', 'Anxiang');
insert into tienda (id_tienda, direccion, ciudad) values (605, '11th Floor', 'Ancasti');
insert into tienda (id_tienda, direccion, ciudad) values (606, '10th Floor', 'Tomas');
insert into tienda (id_tienda, direccion, ciudad) values (607, '1st Floor', 'Andrijevica');
insert into tienda (id_tienda, direccion, ciudad) values (608, 'Suite 7', 'Franco da Rocha');
insert into tienda (id_tienda, direccion, ciudad) values (609, 'Suite 67', 'Kukulu');
insert into tienda (id_tienda, direccion, ciudad) values (610, 'Room 152', 'Doljo');
insert into tienda (id_tienda, direccion, ciudad) values (611, 'Suite 65', 'Dabu');
insert into tienda (id_tienda, direccion, ciudad) values (612, 'Room 1080', 'Solna');
insert into tienda (id_tienda, direccion, ciudad) values (613, 'PO Box 19786', 'Praia da Vitória');
insert into tienda (id_tienda, direccion, ciudad) values (614, 'Apt 486', 'Zhongzhai');
insert into tienda (id_tienda, direccion, ciudad) values (615, 'Room 1037', 'Donglu');
insert into tienda (id_tienda, direccion, ciudad) values (616, '15th Floor', 'Kousséri');
insert into tienda (id_tienda, direccion, ciudad) values (617, '6th Floor', 'Olhos de Água');
insert into tienda (id_tienda, direccion, ciudad) values (618, 'PO Box 34580', 'Huntington Beach');
insert into tienda (id_tienda, direccion, ciudad) values (619, 'Suite 15', 'Waśniów');
insert into tienda (id_tienda, direccion, ciudad) values (620, 'Room 1437', 'Monte Plata');
insert into tienda (id_tienda, direccion, ciudad) values (621, 'Apt 276', 'Ipauçu');
insert into tienda (id_tienda, direccion, ciudad) values (622, 'Room 972', 'Kuala Lumpur');
insert into tienda (id_tienda, direccion, ciudad) values (623, '12th Floor', 'Eleftheroúpolis');
insert into tienda (id_tienda, direccion, ciudad) values (624, 'PO Box 35406', 'Briceni');
insert into tienda (id_tienda, direccion, ciudad) values (625, 'PO Box 17757', 'Welkom');
insert into tienda (id_tienda, direccion, ciudad) values (626, 'Room 352', 'Mehmand Chak');
insert into tienda (id_tienda, direccion, ciudad) values (627, 'Apt 877', 'Mahābād');
insert into tienda (id_tienda, direccion, ciudad) values (628, 'Suite 17', 'Liugong');
insert into tienda (id_tienda, direccion, ciudad) values (629, 'Suite 16', 'Cabanbanan');
insert into tienda (id_tienda, direccion, ciudad) values (630, 'Suite 38', 'Changfa');
insert into tienda (id_tienda, direccion, ciudad) values (631, 'PO Box 66025', 'Daşoguz');
insert into tienda (id_tienda, direccion, ciudad) values (632, 'PO Box 57264', 'Nancheng');
insert into tienda (id_tienda, direccion, ciudad) values (633, 'Apt 1556', 'Vila Moreira');
insert into tienda (id_tienda, direccion, ciudad) values (634, 'Room 654', 'Miami');
insert into tienda (id_tienda, direccion, ciudad) values (635, 'Room 222', 'Zvëzdnyy');
insert into tienda (id_tienda, direccion, ciudad) values (636, 'Apt 816', 'Nioro');
insert into tienda (id_tienda, direccion, ciudad) values (637, 'PO Box 27348', 'Tanashichō');
insert into tienda (id_tienda, direccion, ciudad) values (638, '13th Floor', 'Majie');
insert into tienda (id_tienda, direccion, ciudad) values (639, '19th Floor', 'Mongaguá');
insert into tienda (id_tienda, direccion, ciudad) values (640, 'Room 1269', 'Phalaborwa');
insert into tienda (id_tienda, direccion, ciudad) values (641, '4th Floor', 'Bayuin');
insert into tienda (id_tienda, direccion, ciudad) values (642, 'Suite 95', 'Wuyahe');
insert into tienda (id_tienda, direccion, ciudad) values (643, 'Suite 45', 'Ţubarjal');
insert into tienda (id_tienda, direccion, ciudad) values (644, 'Apt 1277', 'Gordeyevka');
insert into tienda (id_tienda, direccion, ciudad) values (645, '1st Floor', 'Alilem');
insert into tienda (id_tienda, direccion, ciudad) values (646, 'Apt 650', 'Stari Bar');
insert into tienda (id_tienda, direccion, ciudad) values (647, 'PO Box 88424', 'Plácido de Castro');
insert into tienda (id_tienda, direccion, ciudad) values (648, 'Suite 56', 'Rrapë');
insert into tienda (id_tienda, direccion, ciudad) values (649, '5th Floor', 'Pan de Azúcar');
insert into tienda (id_tienda, direccion, ciudad) values (650, 'Apt 1138', 'Dubravica');
insert into tienda (id_tienda, direccion, ciudad) values (651, 'Room 1395', 'Muke');
insert into tienda (id_tienda, direccion, ciudad) values (652, 'Suite 24', 'Bangxi');
insert into tienda (id_tienda, direccion, ciudad) values (653, 'Room 474', 'Cái Dầu');
insert into tienda (id_tienda, direccion, ciudad) values (654, 'Suite 56', 'Calebasses');
insert into tienda (id_tienda, direccion, ciudad) values (655, 'Apt 332', 'Pucangkrajan');
insert into tienda (id_tienda, direccion, ciudad) values (656, 'Suite 86', 'Krasnyy Oktyabr’');
insert into tienda (id_tienda, direccion, ciudad) values (657, '20th Floor', 'Alvito de São Pedro');
insert into tienda (id_tienda, direccion, ciudad) values (658, 'PO Box 35497', 'Sandnes');
insert into tienda (id_tienda, direccion, ciudad) values (659, 'PO Box 7473', 'Kitob');
insert into tienda (id_tienda, direccion, ciudad) values (660, 'PO Box 55446', 'Perivólia');
insert into tienda (id_tienda, direccion, ciudad) values (661, 'Suite 17', 'Tongchuan');
insert into tienda (id_tienda, direccion, ciudad) values (662, 'PO Box 44140', 'Alakak');
insert into tienda (id_tienda, direccion, ciudad) values (663, 'Room 1622', 'Yixi');
insert into tienda (id_tienda, direccion, ciudad) values (664, '6th Floor', 'Zhangcun');
insert into tienda (id_tienda, direccion, ciudad) values (665, '12th Floor', 'Stavyshche');
insert into tienda (id_tienda, direccion, ciudad) values (666, 'Apt 1929', 'Jakšić');
insert into tienda (id_tienda, direccion, ciudad) values (667, 'Suite 51', 'Adolfo Lopez Mateos');
insert into tienda (id_tienda, direccion, ciudad) values (668, 'Suite 54', 'Puerto Boyacá');
insert into tienda (id_tienda, direccion, ciudad) values (669, '16th Floor', 'Buk');
insert into tienda (id_tienda, direccion, ciudad) values (670, 'PO Box 36030', 'Dailekh');
insert into tienda (id_tienda, direccion, ciudad) values (671, 'PO Box 37968', 'Eskilstuna');
insert into tienda (id_tienda, direccion, ciudad) values (672, '17th Floor', 'Matsumoto');
insert into tienda (id_tienda, direccion, ciudad) values (673, 'Suite 69', 'Colorado Springs');
insert into tienda (id_tienda, direccion, ciudad) values (674, '4th Floor', 'Coaticook');
insert into tienda (id_tienda, direccion, ciudad) values (675, 'PO Box 92356', 'Algoz');
insert into tienda (id_tienda, direccion, ciudad) values (676, 'PO Box 23745', 'Kantyshevo');
insert into tienda (id_tienda, direccion, ciudad) values (677, 'Apt 644', 'Shangying');
insert into tienda (id_tienda, direccion, ciudad) values (678, 'Apt 878', 'Iyo');
insert into tienda (id_tienda, direccion, ciudad) values (679, 'Room 1987', 'Biga');
insert into tienda (id_tienda, direccion, ciudad) values (680, 'Apt 1659', 'Valença do Piauí');
insert into tienda (id_tienda, direccion, ciudad) values (681, 'PO Box 19297', 'Masaling');
insert into tienda (id_tienda, direccion, ciudad) values (682, '14th Floor', 'Nancy');
insert into tienda (id_tienda, direccion, ciudad) values (683, 'Room 1024', 'Orzesze');
insert into tienda (id_tienda, direccion, ciudad) values (684, 'Room 894', 'Saitama');
insert into tienda (id_tienda, direccion, ciudad) values (685, 'Room 1756', 'Saint-Denis');
insert into tienda (id_tienda, direccion, ciudad) values (686, 'Suite 68', 'Hacıqabul');
insert into tienda (id_tienda, direccion, ciudad) values (687, 'PO Box 77219', 'Bobrovka');
insert into tienda (id_tienda, direccion, ciudad) values (688, 'Apt 1424', 'Jamalteca');
insert into tienda (id_tienda, direccion, ciudad) values (689, '9th Floor', 'Kraśnik');
insert into tienda (id_tienda, direccion, ciudad) values (690, 'Apt 1520', 'Niort');
insert into tienda (id_tienda, direccion, ciudad) values (691, 'Suite 79', 'Hyltebruk');
insert into tienda (id_tienda, direccion, ciudad) values (692, '8th Floor', 'New Glasgow');
insert into tienda (id_tienda, direccion, ciudad) values (693, 'PO Box 61506', 'Mengmeng');
insert into tienda (id_tienda, direccion, ciudad) values (694, 'PO Box 96876', 'Yeni Suraxanı');
insert into tienda (id_tienda, direccion, ciudad) values (695, 'Room 1942', 'Setro');
insert into tienda (id_tienda, direccion, ciudad) values (696, 'Suite 78', 'Huanza');
insert into tienda (id_tienda, direccion, ciudad) values (697, 'Room 675', 'San Patricio');
insert into tienda (id_tienda, direccion, ciudad) values (698, 'Suite 40', 'Arendal');
insert into tienda (id_tienda, direccion, ciudad) values (699, '9th Floor', 'Kurkino');
insert into tienda (id_tienda, direccion, ciudad) values (700, '7th Floor', 'Ḩalḩūl');
insert into tienda (id_tienda, direccion, ciudad) values (701, 'PO Box 27741', 'Zengji');
insert into tienda (id_tienda, direccion, ciudad) values (702, 'Room 1777', 'Turi');
insert into tienda (id_tienda, direccion, ciudad) values (703, 'Suite 57', 'Krajan Bakalan');
insert into tienda (id_tienda, direccion, ciudad) values (704, 'Room 1810', 'Nuku‘alofa');
insert into tienda (id_tienda, direccion, ciudad) values (705, '18th Floor', 'Sanban');
insert into tienda (id_tienda, direccion, ciudad) values (706, 'Room 1935', 'Krzynowłoga Mała');
insert into tienda (id_tienda, direccion, ciudad) values (707, '17th Floor', 'Magisterial');
insert into tienda (id_tienda, direccion, ciudad) values (708, 'Apt 760', 'Wonosari');
insert into tienda (id_tienda, direccion, ciudad) values (709, 'Apt 1400', 'Chatian');
insert into tienda (id_tienda, direccion, ciudad) values (710, 'Room 1490', 'Sinarjaya');
insert into tienda (id_tienda, direccion, ciudad) values (711, 'Suite 67', 'Sanxianling');
insert into tienda (id_tienda, direccion, ciudad) values (712, 'Suite 10', 'Nueva Arica');
insert into tienda (id_tienda, direccion, ciudad) values (713, '20th Floor', 'Sande São Martinho');
insert into tienda (id_tienda, direccion, ciudad) values (714, 'Suite 98', 'Ludishan');
insert into tienda (id_tienda, direccion, ciudad) values (715, 'Apt 392', 'Sidem');
insert into tienda (id_tienda, direccion, ciudad) values (716, '19th Floor', 'Harstad');
insert into tienda (id_tienda, direccion, ciudad) values (717, 'PO Box 98416', 'Khlung');
insert into tienda (id_tienda, direccion, ciudad) values (718, 'Suite 38', 'Paranavaí');
insert into tienda (id_tienda, direccion, ciudad) values (719, 'Suite 75', 'Gakem');
insert into tienda (id_tienda, direccion, ciudad) values (720, 'Room 594', 'Kamenné Žehrovice');
insert into tienda (id_tienda, direccion, ciudad) values (721, 'Apt 1242', 'Verkhnyachka');
insert into tienda (id_tienda, direccion, ciudad) values (722, '2nd Floor', 'Bolboc');
insert into tienda (id_tienda, direccion, ciudad) values (723, 'Apt 24', 'Dawan');
insert into tienda (id_tienda, direccion, ciudad) values (724, '20th Floor', 'Los Charrúas');
insert into tienda (id_tienda, direccion, ciudad) values (725, 'PO Box 12956', 'Sagarejo');
insert into tienda (id_tienda, direccion, ciudad) values (726, 'Suite 88', 'Vista Hermosa');
insert into tienda (id_tienda, direccion, ciudad) values (727, 'Suite 100', 'Araçatuba');
insert into tienda (id_tienda, direccion, ciudad) values (728, 'Room 1017', 'Qarah Bāgh Bāzār');
insert into tienda (id_tienda, direccion, ciudad) values (729, 'Room 1721', 'Diyarb Najm');
insert into tienda (id_tienda, direccion, ciudad) values (730, '6th Floor', 'Casilda');
insert into tienda (id_tienda, direccion, ciudad) values (731, 'Suite 90', 'Ndélé');
insert into tienda (id_tienda, direccion, ciudad) values (732, 'Room 730', 'Chechenglu');
insert into tienda (id_tienda, direccion, ciudad) values (733, '6th Floor', 'Bazzāryah');
insert into tienda (id_tienda, direccion, ciudad) values (734, 'Apt 815', 'Khlong Luang');
insert into tienda (id_tienda, direccion, ciudad) values (735, '3rd Floor', 'Krajan Langenharjo');
insert into tienda (id_tienda, direccion, ciudad) values (736, 'Suite 97', 'Suicheng');
insert into tienda (id_tienda, direccion, ciudad) values (737, 'Suite 20', 'Kratié');
insert into tienda (id_tienda, direccion, ciudad) values (738, 'Apt 123', 'Thạnh Hóa');
insert into tienda (id_tienda, direccion, ciudad) values (739, '11th Floor', 'Perstorp');
insert into tienda (id_tienda, direccion, ciudad) values (740, 'Suite 78', 'Ndom');
insert into tienda (id_tienda, direccion, ciudad) values (741, 'Room 1673', 'Mashan');
insert into tienda (id_tienda, direccion, ciudad) values (742, 'Apt 435', 'Lefengzhen');
insert into tienda (id_tienda, direccion, ciudad) values (743, 'Suite 76', 'Dal’nerechensk');
insert into tienda (id_tienda, direccion, ciudad) values (744, 'Apt 1501', 'Dar Chabanne');
insert into tienda (id_tienda, direccion, ciudad) values (745, 'PO Box 25762', 'Nepeña');
insert into tienda (id_tienda, direccion, ciudad) values (746, 'Apt 1327', 'Portela');
insert into tienda (id_tienda, direccion, ciudad) values (747, 'Suite 74', 'Carleton-sur-Mer');
insert into tienda (id_tienda, direccion, ciudad) values (748, 'Suite 90', 'Vellinge');
insert into tienda (id_tienda, direccion, ciudad) values (749, 'PO Box 29331', 'Shangjing');
insert into tienda (id_tienda, direccion, ciudad) values (750, '2nd Floor', 'Duyanggang');
insert into tienda (id_tienda, direccion, ciudad) values (751, 'Apt 1314', 'Izobil’nyy');
insert into tienda (id_tienda, direccion, ciudad) values (752, 'Suite 71', 'Řehlovice');
insert into tienda (id_tienda, direccion, ciudad) values (753, 'Room 1821', 'Ust’-Labinsk');
insert into tienda (id_tienda, direccion, ciudad) values (754, '11th Floor', 'Mayskiy');
insert into tienda (id_tienda, direccion, ciudad) values (755, '4th Floor', 'Al Qubbah');
insert into tienda (id_tienda, direccion, ciudad) values (756, 'PO Box 10178', 'Pita Kotte');
insert into tienda (id_tienda, direccion, ciudad) values (757, 'Suite 65', 'Água Preta');
insert into tienda (id_tienda, direccion, ciudad) values (758, '7th Floor', 'João Câmara');
insert into tienda (id_tienda, direccion, ciudad) values (759, 'PO Box 13798', 'Qishui');
insert into tienda (id_tienda, direccion, ciudad) values (760, 'Apt 48', 'Dawan');
insert into tienda (id_tienda, direccion, ciudad) values (761, 'Suite 13', 'Desovo');
insert into tienda (id_tienda, direccion, ciudad) values (762, 'Room 1828', 'Kaduranca');
insert into tienda (id_tienda, direccion, ciudad) values (763, 'Room 1660', 'San Jose');
insert into tienda (id_tienda, direccion, ciudad) values (764, 'PO Box 77780', 'Annecy');
insert into tienda (id_tienda, direccion, ciudad) values (765, 'PO Box 64908', 'Uzda');
insert into tienda (id_tienda, direccion, ciudad) values (766, 'Room 861', 'Najrān');
insert into tienda (id_tienda, direccion, ciudad) values (767, 'Room 1482', 'Nova Venécia');
insert into tienda (id_tienda, direccion, ciudad) values (768, 'Apt 1796', 'Fiditi');
insert into tienda (id_tienda, direccion, ciudad) values (769, 'PO Box 3121', 'Mingcheng');
insert into tienda (id_tienda, direccion, ciudad) values (770, 'Suite 10', 'Antou');
insert into tienda (id_tienda, direccion, ciudad) values (771, '12th Floor', 'Dadian');
insert into tienda (id_tienda, direccion, ciudad) values (772, 'Room 1235', 'Gunungangka');
insert into tienda (id_tienda, direccion, ciudad) values (773, 'PO Box 69123', 'Maliq');
insert into tienda (id_tienda, direccion, ciudad) values (774, 'Room 1751', 'Gislaved');
insert into tienda (id_tienda, direccion, ciudad) values (775, 'Room 741', 'Nuevo Amanecer');
insert into tienda (id_tienda, direccion, ciudad) values (776, 'Apt 220', 'Weitang');
insert into tienda (id_tienda, direccion, ciudad) values (777, 'Apt 567', 'Malie');
insert into tienda (id_tienda, direccion, ciudad) values (778, 'Suite 76', 'Saint-Gratien');
insert into tienda (id_tienda, direccion, ciudad) values (779, 'Apt 1026', 'Barra do Garças');
insert into tienda (id_tienda, direccion, ciudad) values (780, '9th Floor', 'Nyinqug');
insert into tienda (id_tienda, direccion, ciudad) values (781, '14th Floor', 'Jiangzhang');
insert into tienda (id_tienda, direccion, ciudad) values (782, 'Room 293', 'Kunów');
insert into tienda (id_tienda, direccion, ciudad) values (783, 'PO Box 21121', 'Skellefteå');
insert into tienda (id_tienda, direccion, ciudad) values (784, 'PO Box 13318', 'Dranoc');
insert into tienda (id_tienda, direccion, ciudad) values (785, 'Room 206', 'Santa Ana');
insert into tienda (id_tienda, direccion, ciudad) values (786, '10th Floor', 'San Pedro de Lloc');
insert into tienda (id_tienda, direccion, ciudad) values (787, 'Suite 39', 'Nelidovo');
insert into tienda (id_tienda, direccion, ciudad) values (788, '8th Floor', 'Książki');
insert into tienda (id_tienda, direccion, ciudad) values (789, 'Room 288', 'Ciburial');
insert into tienda (id_tienda, direccion, ciudad) values (790, 'Suite 51', 'Vodňany');
insert into tienda (id_tienda, direccion, ciudad) values (791, 'Suite 69', 'Rajadesa');
insert into tienda (id_tienda, direccion, ciudad) values (792, 'Suite 42', 'Fuxing');
insert into tienda (id_tienda, direccion, ciudad) values (793, '6th Floor', 'Havirga');
insert into tienda (id_tienda, direccion, ciudad) values (794, 'Suite 5', 'Foundiougne');
insert into tienda (id_tienda, direccion, ciudad) values (795, 'Suite 90', 'Diên Khánh');
insert into tienda (id_tienda, direccion, ciudad) values (796, '18th Floor', 'Yuncheng');
insert into tienda (id_tienda, direccion, ciudad) values (797, 'PO Box 25061', 'Strazhitsa');
insert into tienda (id_tienda, direccion, ciudad) values (798, 'Apt 655', 'Kuala Lumpur');
insert into tienda (id_tienda, direccion, ciudad) values (799, 'Apt 127', 'Zarasai');
insert into tienda (id_tienda, direccion, ciudad) values (800, 'Suite 16', 'Mercedes');
insert into tienda (id_tienda, direccion, ciudad) values (801, 'Suite 66', 'Ol Kalou');
insert into tienda (id_tienda, direccion, ciudad) values (802, 'PO Box 13260', 'Gore');
insert into tienda (id_tienda, direccion, ciudad) values (803, '5th Floor', 'Miejska Górka');
insert into tienda (id_tienda, direccion, ciudad) values (804, 'Apt 566', 'Lloque');
insert into tienda (id_tienda, direccion, ciudad) values (805, 'PO Box 28406', 'Agadez');
insert into tienda (id_tienda, direccion, ciudad) values (806, 'Room 272', 'Borucin');
insert into tienda (id_tienda, direccion, ciudad) values (807, 'Room 567', 'Pasirjaya');
insert into tienda (id_tienda, direccion, ciudad) values (808, 'Room 461', 'Tupaciguara');
insert into tienda (id_tienda, direccion, ciudad) values (809, 'Suite 29', 'Kayar');
insert into tienda (id_tienda, direccion, ciudad) values (810, 'Suite 9', 'Västervik');
insert into tienda (id_tienda, direccion, ciudad) values (811, 'Room 1417', 'Lomboy');
insert into tienda (id_tienda, direccion, ciudad) values (812, '5th Floor', 'Unidos');
insert into tienda (id_tienda, direccion, ciudad) values (813, '20th Floor', 'Alcaldedíaz');
insert into tienda (id_tienda, direccion, ciudad) values (814, 'PO Box 16893', 'Osek nad Bečvou');
insert into tienda (id_tienda, direccion, ciudad) values (815, 'Room 1050', 'Kelodan');
insert into tienda (id_tienda, direccion, ciudad) values (816, 'Apt 606', 'Carriedo');
insert into tienda (id_tienda, direccion, ciudad) values (817, 'Room 354', '‘Amrān');
insert into tienda (id_tienda, direccion, ciudad) values (818, 'Room 944', 'Hongcao');
insert into tienda (id_tienda, direccion, ciudad) values (819, 'Suite 32', 'Paritjunus');
insert into tienda (id_tienda, direccion, ciudad) values (820, '2nd Floor', 'Metz');
insert into tienda (id_tienda, direccion, ciudad) values (821, 'Apt 210', 'Huixing');
insert into tienda (id_tienda, direccion, ciudad) values (822, 'PO Box 1671', 'Ban Selaphum');
insert into tienda (id_tienda, direccion, ciudad) values (823, '9th Floor', 'Las Lajas');
insert into tienda (id_tienda, direccion, ciudad) values (824, 'Room 530', 'Bistrica ob Sotli');
insert into tienda (id_tienda, direccion, ciudad) values (825, 'Apt 1362', 'Honghuatao');
insert into tienda (id_tienda, direccion, ciudad) values (826, 'Room 1849', 'Kandava');
insert into tienda (id_tienda, direccion, ciudad) values (827, 'Apt 1556', 'Miki');
insert into tienda (id_tienda, direccion, ciudad) values (828, 'Suite 57', 'Businovo');
insert into tienda (id_tienda, direccion, ciudad) values (829, 'Suite 80', 'Pocito');
insert into tienda (id_tienda, direccion, ciudad) values (830, 'Suite 80', 'Sansanné-Mango');
insert into tienda (id_tienda, direccion, ciudad) values (831, 'Apt 745', 'Martapura');
insert into tienda (id_tienda, direccion, ciudad) values (832, 'Room 11', 'Jarry');
insert into tienda (id_tienda, direccion, ciudad) values (833, 'Apt 1154', 'Sveg');
insert into tienda (id_tienda, direccion, ciudad) values (834, 'Apt 747', 'Meishan');
insert into tienda (id_tienda, direccion, ciudad) values (835, 'Room 1000', 'Berlin');
insert into tienda (id_tienda, direccion, ciudad) values (836, 'PO Box 14837', 'Kalyny');
insert into tienda (id_tienda, direccion, ciudad) values (837, 'Room 1871', 'Kondangrege');
insert into tienda (id_tienda, direccion, ciudad) values (838, '9th Floor', 'Anse Boileau');
insert into tienda (id_tienda, direccion, ciudad) values (839, '4th Floor', 'Pesucen');
insert into tienda (id_tienda, direccion, ciudad) values (840, 'Apt 1011', 'Benito Juarez');
insert into tienda (id_tienda, direccion, ciudad) values (841, 'PO Box 9122', 'Isiro');
insert into tienda (id_tienda, direccion, ciudad) values (842, '13th Floor', 'Pakalongan');
insert into tienda (id_tienda, direccion, ciudad) values (843, 'Suite 17', 'Yongfeng');
insert into tienda (id_tienda, direccion, ciudad) values (844, 'PO Box 82211', 'Baoji');
insert into tienda (id_tienda, direccion, ciudad) values (845, 'PO Box 5798', 'Taekas');
insert into tienda (id_tienda, direccion, ciudad) values (846, 'PO Box 36392', 'Bugcaon');
insert into tienda (id_tienda, direccion, ciudad) values (847, 'Room 738', 'Mekarsari');
insert into tienda (id_tienda, direccion, ciudad) values (848, 'Apt 701', 'Jimusa’er');
insert into tienda (id_tienda, direccion, ciudad) values (849, '15th Floor', 'Suchedniów');
insert into tienda (id_tienda, direccion, ciudad) values (850, 'Room 1579', 'Askim');
insert into tienda (id_tienda, direccion, ciudad) values (851, '10th Floor', 'Mafang');
insert into tienda (id_tienda, direccion, ciudad) values (852, 'PO Box 75903', 'Jingnao');
insert into tienda (id_tienda, direccion, ciudad) values (853, 'Suite 92', 'Qal‘eh Ganj');
insert into tienda (id_tienda, direccion, ciudad) values (854, 'PO Box 13549', 'Santa Bárbara');
insert into tienda (id_tienda, direccion, ciudad) values (855, '14th Floor', 'Marčelji');
insert into tienda (id_tienda, direccion, ciudad) values (856, 'Room 1471', 'Kuivaniemi');
insert into tienda (id_tienda, direccion, ciudad) values (857, 'Room 779', 'Wadi Kidul');
insert into tienda (id_tienda, direccion, ciudad) values (858, 'Suite 66', 'Pervomays’ke');
insert into tienda (id_tienda, direccion, ciudad) values (859, 'Room 327', 'Carrazeda de Ansiães');
insert into tienda (id_tienda, direccion, ciudad) values (860, '1st Floor', 'Ivyanyets');
insert into tienda (id_tienda, direccion, ciudad) values (861, '14th Floor', 'Masatepe');
insert into tienda (id_tienda, direccion, ciudad) values (862, '8th Floor', 'Arauco');
insert into tienda (id_tienda, direccion, ciudad) values (863, 'Apt 1668', 'Pyatnitskoye');
insert into tienda (id_tienda, direccion, ciudad) values (864, 'PO Box 10841', 'Kozakai-chō');
insert into tienda (id_tienda, direccion, ciudad) values (865, 'PO Box 76804', 'Grazhdanskoye');
insert into tienda (id_tienda, direccion, ciudad) values (866, 'Suite 71', 'Causwagan');
insert into tienda (id_tienda, direccion, ciudad) values (867, 'Suite 96', 'Luoyang');
insert into tienda (id_tienda, direccion, ciudad) values (868, 'PO Box 28920', 'Kapan');
insert into tienda (id_tienda, direccion, ciudad) values (869, '14th Floor', 'Huangtan');
insert into tienda (id_tienda, direccion, ciudad) values (870, 'PO Box 84800', 'Marseille');
insert into tienda (id_tienda, direccion, ciudad) values (871, 'Apt 611', 'Kara');
insert into tienda (id_tienda, direccion, ciudad) values (872, '16th Floor', 'Kauhan');
insert into tienda (id_tienda, direccion, ciudad) values (873, 'Suite 90', 'Kez');
insert into tienda (id_tienda, direccion, ciudad) values (874, 'Room 1541', 'Szynwałd');
insert into tienda (id_tienda, direccion, ciudad) values (875, '3rd Floor', 'Sangali');
insert into tienda (id_tienda, direccion, ciudad) values (876, 'Suite 92', 'Yuanmou');
insert into tienda (id_tienda, direccion, ciudad) values (877, 'Room 1421', 'Drammen');
insert into tienda (id_tienda, direccion, ciudad) values (878, 'PO Box 3172', 'Paris 02');
insert into tienda (id_tienda, direccion, ciudad) values (879, 'Room 1198', 'Kefang');
insert into tienda (id_tienda, direccion, ciudad) values (880, 'Suite 84', 'Rezé');
insert into tienda (id_tienda, direccion, ciudad) values (881, '8th Floor', 'Shuangmiaojie');
insert into tienda (id_tienda, direccion, ciudad) values (882, 'Room 1019', 'Sabunçu');
insert into tienda (id_tienda, direccion, ciudad) values (883, 'Room 1859', 'Senahú');
insert into tienda (id_tienda, direccion, ciudad) values (884, 'Suite 71', 'Xinfengjie');
insert into tienda (id_tienda, direccion, ciudad) values (885, 'Suite 99', 'Leonidovo');
insert into tienda (id_tienda, direccion, ciudad) values (886, '7th Floor', 'Al Buţayḩah');
insert into tienda (id_tienda, direccion, ciudad) values (887, 'Apt 962', 'Jurh');
insert into tienda (id_tienda, direccion, ciudad) values (888, 'Suite 52', 'Nyakhachava');
insert into tienda (id_tienda, direccion, ciudad) values (889, 'Suite 40', 'Perico');
insert into tienda (id_tienda, direccion, ciudad) values (890, 'Apt 1743', 'Öndörhoshuu');
insert into tienda (id_tienda, direccion, ciudad) values (891, 'Suite 5', 'Palencia');
insert into tienda (id_tienda, direccion, ciudad) values (892, 'Room 897', 'Sar-e Pul');
insert into tienda (id_tienda, direccion, ciudad) values (893, 'Room 1452', 'Agía Varvára');
insert into tienda (id_tienda, direccion, ciudad) values (894, 'Apt 1919', 'Nedryhayliv');
insert into tienda (id_tienda, direccion, ciudad) values (895, 'Suite 15', 'Símantra');
insert into tienda (id_tienda, direccion, ciudad) values (896, 'PO Box 54257', 'Brejo Santo');
insert into tienda (id_tienda, direccion, ciudad) values (897, 'PO Box 45335', 'Goranboy');
insert into tienda (id_tienda, direccion, ciudad) values (898, 'PO Box 99628', 'Pancheng');
insert into tienda (id_tienda, direccion, ciudad) values (899, 'Room 1829', 'Niška Banja');
insert into tienda (id_tienda, direccion, ciudad) values (900, 'Apt 230', 'Itaúna');
insert into tienda (id_tienda, direccion, ciudad) values (901, 'Room 393', 'Seleuš');
insert into tienda (id_tienda, direccion, ciudad) values (902, 'Suite 60', 'Huangbei');
insert into tienda (id_tienda, direccion, ciudad) values (903, '16th Floor', 'Lebedyn');
insert into tienda (id_tienda, direccion, ciudad) values (904, 'Room 1498', 'Uva');
insert into tienda (id_tienda, direccion, ciudad) values (905, 'Apt 1983', 'Pevek');
insert into tienda (id_tienda, direccion, ciudad) values (906, '5th Floor', 'Vila Verde');
insert into tienda (id_tienda, direccion, ciudad) values (907, 'Suite 96', 'Shi’ao');
insert into tienda (id_tienda, direccion, ciudad) values (908, 'Room 723', 'La Coipa');
insert into tienda (id_tienda, direccion, ciudad) values (909, 'Suite 39', 'Blagaj');
insert into tienda (id_tienda, direccion, ciudad) values (910, 'PO Box 96252', 'Turus');
insert into tienda (id_tienda, direccion, ciudad) values (911, '10th Floor', 'Huili Chengguanzhen');
insert into tienda (id_tienda, direccion, ciudad) values (912, 'Apt 154', 'Dobrich');
insert into tienda (id_tienda, direccion, ciudad) values (913, 'Suite 91', 'Danjiangkou');
insert into tienda (id_tienda, direccion, ciudad) values (914, 'Suite 89', 'Hongzhou');
insert into tienda (id_tienda, direccion, ciudad) values (915, '18th Floor', 'Javhlant');
insert into tienda (id_tienda, direccion, ciudad) values (916, 'Suite 11', 'Nikol’sk');
insert into tienda (id_tienda, direccion, ciudad) values (917, 'Room 1218', 'Dole');
insert into tienda (id_tienda, direccion, ciudad) values (918, 'Suite 13', 'Roa');
insert into tienda (id_tienda, direccion, ciudad) values (919, '16th Floor', 'Prakhon Chai');
insert into tienda (id_tienda, direccion, ciudad) values (920, 'Apt 1612', 'Vukovar');
insert into tienda (id_tienda, direccion, ciudad) values (921, '16th Floor', 'Krasnorechenskiy');
insert into tienda (id_tienda, direccion, ciudad) values (922, 'Suite 45', 'Storuman');
insert into tienda (id_tienda, direccion, ciudad) values (923, '10th Floor', 'Shadrinsk');
insert into tienda (id_tienda, direccion, ciudad) values (924, 'Room 270', 'Deba Habe');
insert into tienda (id_tienda, direccion, ciudad) values (925, 'PO Box 3262', 'Pawonków');
insert into tienda (id_tienda, direccion, ciudad) values (926, '2nd Floor', 'Mourelos');
insert into tienda (id_tienda, direccion, ciudad) values (927, '9th Floor', 'Kondangrege');
insert into tienda (id_tienda, direccion, ciudad) values (928, 'PO Box 43668', 'Zheleznovodsk');
insert into tienda (id_tienda, direccion, ciudad) values (929, 'Apt 1721', 'Fengshan');
insert into tienda (id_tienda, direccion, ciudad) values (930, 'PO Box 70741', 'Gradići');
insert into tienda (id_tienda, direccion, ciudad) values (931, 'Apt 1345', 'Zemlyansk');
insert into tienda (id_tienda, direccion, ciudad) values (932, 'Apt 1088', 'Kissimmee');
insert into tienda (id_tienda, direccion, ciudad) values (933, '13th Floor', 'Dongtian');
insert into tienda (id_tienda, direccion, ciudad) values (934, 'Suite 19', 'Wierzchowo');
insert into tienda (id_tienda, direccion, ciudad) values (935, 'PO Box 94344', 'Serra da Boa Viagem');
insert into tienda (id_tienda, direccion, ciudad) values (936, 'PO Box 45971', 'Cucuyagua');
insert into tienda (id_tienda, direccion, ciudad) values (937, 'Room 145', 'San Francisco');
insert into tienda (id_tienda, direccion, ciudad) values (938, 'Suite 47', 'Boca do Acre');
insert into tienda (id_tienda, direccion, ciudad) values (939, '18th Floor', 'Studénka');
insert into tienda (id_tienda, direccion, ciudad) values (940, 'PO Box 478', 'Ōfunato');
insert into tienda (id_tienda, direccion, ciudad) values (941, 'Apt 906', 'Lenningen');
insert into tienda (id_tienda, direccion, ciudad) values (942, 'Apt 319', 'Strání');
insert into tienda (id_tienda, direccion, ciudad) values (943, 'PO Box 26737', 'Šentrupert');
insert into tienda (id_tienda, direccion, ciudad) values (944, 'PO Box 6644', 'Mulhouse');
insert into tienda (id_tienda, direccion, ciudad) values (945, '15th Floor', 'Calape');
insert into tienda (id_tienda, direccion, ciudad) values (946, 'Room 637', 'Shanhaiguan');
insert into tienda (id_tienda, direccion, ciudad) values (947, 'Apt 1979', 'San Rafael Abajo');
insert into tienda (id_tienda, direccion, ciudad) values (948, 'PO Box 82405', 'Oras');
insert into tienda (id_tienda, direccion, ciudad) values (949, 'PO Box 96249', 'Compostela');
insert into tienda (id_tienda, direccion, ciudad) values (950, 'Suite 30', 'Noisy-le-Grand');
insert into tienda (id_tienda, direccion, ciudad) values (951, 'Suite 9', 'Lucé');
insert into tienda (id_tienda, direccion, ciudad) values (952, 'Suite 71', 'Star’');
insert into tienda (id_tienda, direccion, ciudad) values (953, 'Apt 352', 'Wushan');
insert into tienda (id_tienda, direccion, ciudad) values (954, '11th Floor', 'Bantaeng');
insert into tienda (id_tienda, direccion, ciudad) values (955, 'Apt 1462', 'Bao’an');
insert into tienda (id_tienda, direccion, ciudad) values (956, 'Apt 850', 'Cikaung');
insert into tienda (id_tienda, direccion, ciudad) values (957, 'PO Box 91203', 'Jinghai');
insert into tienda (id_tienda, direccion, ciudad) values (958, 'PO Box 85537', 'Sumbergayam');
insert into tienda (id_tienda, direccion, ciudad) values (959, '13th Floor', 'Tianhe');
insert into tienda (id_tienda, direccion, ciudad) values (960, 'Room 983', 'Ketangi');
insert into tienda (id_tienda, direccion, ciudad) values (961, 'Room 558', 'Reshetylivka');
insert into tienda (id_tienda, direccion, ciudad) values (962, '16th Floor', 'Muroran');
insert into tienda (id_tienda, direccion, ciudad) values (963, 'PO Box 57069', 'Araucária');
insert into tienda (id_tienda, direccion, ciudad) values (964, 'Apt 1484', 'Wendo');
insert into tienda (id_tienda, direccion, ciudad) values (965, 'Suite 6', 'Hato Mayor del Rey');
insert into tienda (id_tienda, direccion, ciudad) values (966, 'Apt 1436', 'Myhove');
insert into tienda (id_tienda, direccion, ciudad) values (967, '11th Floor', 'Níkiti');
insert into tienda (id_tienda, direccion, ciudad) values (968, 'Suite 16', 'Centurion');
insert into tienda (id_tienda, direccion, ciudad) values (969, 'PO Box 16242', 'Jonava');
insert into tienda (id_tienda, direccion, ciudad) values (970, 'Apt 1754', 'Lambangan Kulon');
insert into tienda (id_tienda, direccion, ciudad) values (971, 'Apt 1731', 'Nakambala');
insert into tienda (id_tienda, direccion, ciudad) values (972, '13th Floor', 'Kilmacanoge');
insert into tienda (id_tienda, direccion, ciudad) values (973, 'Suite 23', 'Bulu');
insert into tienda (id_tienda, direccion, ciudad) values (974, '2nd Floor', 'Sangkulirang');
insert into tienda (id_tienda, direccion, ciudad) values (975, 'Suite 14', 'Gardutanjak');
insert into tienda (id_tienda, direccion, ciudad) values (976, 'Apt 1238', 'Wringinsari');
insert into tienda (id_tienda, direccion, ciudad) values (977, 'PO Box 12335', 'Göteborg');
insert into tienda (id_tienda, direccion, ciudad) values (978, 'Apt 757', 'Patong');
insert into tienda (id_tienda, direccion, ciudad) values (979, 'Suite 10', 'La Courneuve');
insert into tienda (id_tienda, direccion, ciudad) values (980, 'Apt 1419', 'Syrskoye');
insert into tienda (id_tienda, direccion, ciudad) values (981, 'PO Box 14560', 'Opočno');
insert into tienda (id_tienda, direccion, ciudad) values (982, '2nd Floor', 'Changzheng');
insert into tienda (id_tienda, direccion, ciudad) values (983, 'PO Box 89866', 'Longyearbyen');
insert into tienda (id_tienda, direccion, ciudad) values (984, '20th Floor', 'Cabra Figa');
insert into tienda (id_tienda, direccion, ciudad) values (985, 'Apt 1393', 'Kāleke Mandi');
insert into tienda (id_tienda, direccion, ciudad) values (986, 'Apt 1342', 'Margen');
insert into tienda (id_tienda, direccion, ciudad) values (987, 'Suite 42', 'Taquara');
insert into tienda (id_tienda, direccion, ciudad) values (988, 'PO Box 26297', 'Thai Charoen');
insert into tienda (id_tienda, direccion, ciudad) values (989, 'Suite 44', 'Qingnianlu');
insert into tienda (id_tienda, direccion, ciudad) values (990, 'Room 1415', 'Hwacheon');
insert into tienda (id_tienda, direccion, ciudad) values (991, 'Room 417', 'Tanda');
insert into tienda (id_tienda, direccion, ciudad) values (992, 'Suite 55', 'Lanckorona');
insert into tienda (id_tienda, direccion, ciudad) values (993, '6th Floor', 'Tagasilay');
insert into tienda (id_tienda, direccion, ciudad) values (994, 'Room 584', 'Mora');
insert into tienda (id_tienda, direccion, ciudad) values (995, 'Room 1682', 'Isfana');
insert into tienda (id_tienda, direccion, ciudad) values (996, 'Apt 854', 'Sumurwaru');
insert into tienda (id_tienda, direccion, ciudad) values (997, 'Apt 240', 'Barreiro do Jaíba');
insert into tienda (id_tienda, direccion, ciudad) values (998, 'Room 1174', 'Corozal');
insert into tienda (id_tienda, direccion, ciudad) values (999, '3rd Floor', 'Buenavista');
insert into tienda (id_tienda, direccion, ciudad) values (1000, 'Room 1027', 'Truskolasy');
